### ISSUE TITLE
News - April 2017

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#122]
This is Liberapay's news thread, its purpose is to help us achieve #29.

cc @liberapay/media-managers

**Comment by Changaco** [comment]
[Liberapay libère les dons !](https://www.tribords.com/?liberapay-interview) (interview in the blog of <https://liberapay.com/buzzistic>)

**Comment by Changaco** [comment]
We now have a Mastodon account: https://mastodon.rocks/@Liberapay

**Comment by Changaco** [comment]
[Pourquoi j’ai créé ma page Liberapay | Le blog de Carl Chenet](https://carlchenet.com/pourquoi-jai-cree-ma-page-liberapay/)

**Comment by Changaco** [comment]
https://twitter.com/liberapaye/status/850289140214247424

> We've joined the #Mastodon decentralized social network! https://mastodon.rocks/@Liberapay
>
> Reminder: we're also on Diaspora* https://framasphere.org/u/liberapay

**Comment by Changaco** [comment]
(And here is my personal account: <https://mastodon.cloud/@Changaco>.)

**Comment by aggsol** [comment]
Will there by a Mastodon pledge function like for twitter?

**Comment by Changaco** [comment]
Yes, as soon as someone implements it…

**Comment by Changaco** [comment]
[Après un an d'activité, Liberapay veut être l'alternative libre pour les dons récurrents](https://www.nextinpact.com/news/104027-apres-an-dactivite-liberapay-veut-etre-alternative-libre-pour-dons-recurrents.htm) (interview in a well-known French media focused on tech) (behind paywall)

**Comment by Changaco** [comment]
https://mastodon.rocks/@Liberapay/221989

> The Chinese subdomain of Liberapay has just been added: https://zh.liberapay.com/ Of course the translation isn't complete yet.
>
> You can help translate Liberapay through Weblate: https://hosted.weblate.org/engage/liberapay/ #i18n
