### ISSUE TITLE
How does the money quarantine work?

### ISSUE THREAD

**Issue by aggsol** [liberapay/salon#123]
For a proper German translation I need more info on the quarantine process. Is the withdrawl just blocked for certain time or is the some kind of escrow?

**Comment by Changaco** [comment]
Quarantine is based on the time of entry of the money into Liberapay. The money in a wallet may seem like a homogeneous amount, but it's actually a sum of virtual "cash bundles", with each bundle having its own date of entry.

The quarantine prevents withdrawing bundles that have entered Liberapay less than 4 weeks (28 days) ago. So, if you have 10 euros in your wallet, and 2.47 of those entered less than 4 weeks ago, then you can't withdraw more than 7.53 euros today.

The time of entry is when the money arrived for the first time in a wallet, from a credit card or bank wire (or any other payment method we may implement in the future), not the time of entry into the wallet of the user who wants to withdraw.

Does that answer your question?

**Comment by aggsol** [comment]
Yes, thank you.
