### ISSUE TITLE
Coordinate Liberapay team takes

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#13]
https://liberapay.com/Liberapay/income/

@MartinDelille, you've been contributing code. @finkiki, you contributed translations before the launch. You should both take €0.01 at the very least.

**Comment by Changaco** [comment]
@aandis Don't hesitate to take a little money from the team too. ;-)

**Comment by aandis** [comment]
haha. thanks for the offer. ;)
I am a little new to the whole *taking* concept so can you brief me on how exactly does it work? I fill in my identity details and then what?

**Comment by aandis** [comment]
Also, though I'll try to contribute as much as possible, I am not sure how regularly I will be able to contribute because of college, personal projects, gratipay and other stuff. So.. if I do start *taking*, is there a minimum amount of work I'd need to do? Because then it won't be right on my part to *take* anything if I am not doing any significant contributions.

**Comment by Changaco** [comment]
Oh, right, you started working on Gratipay after the teams stopped working.

We do have an [About Teams](https://liberapay.com/about/teams) page that you can read, though some people have pointed out that it's not entirely clear.

Basically, you decide how much you take from the team, and the money is transferred to you during payday. You can change your take at any time, so you can raise it when you do more work on Liberapay and lower it when you do less. If we feel someone is taking too much or too little we'll discuss it, that's what this ticket is for.

The minimum you can take is €0.01, and anyone who has contributed to Liberapay deserves at least that (it's a very small amount of money, only 52 cents a year).

> So.. if I do start *taking*, is there a minimum amount of work I'd need to do?

No.

**Comment by aandis** [comment]
> You can change your take at any time, so you can raise it when you do more work on Liberapay and lower it when you do less.

This sounds perfect! :)

**Comment by Changaco** [comment]
> This sounds perfect! :)

It's take-what-you-want remuneration, credit goes to Chad for the original implementation in Gittip. :-)

**Comment by Changaco** [comment]
Ping @Evild67 @KindlyFire @nijel: feel free to take a little money from the team, translators deserve to be paid.

**Comment by Changaco** [comment]
cc @deivid-rodriguez, welcome to the team ;-)

**Comment by deivid-rodriguez** [comment]
Thanks @Changaco , I just setup my 0.01€ take!

**Comment by Changaco** [comment]
We're starting to have some more leftover income now that we're asking users to support us, remember to adjust your takes regularly. ;-)

**Comment by Changaco** [comment]
cc @pgno, welcome to the team ;-)

**Comment by Changaco** [comment]
Payday is tomorrow and there are still 6 euros of leftover right now, so don't forget to raise your takes if you've been underpaying yourself.

**Comment by KindlyFire** [comment]
I think you should take some more too :)

**Comment by Changaco** [comment]
I've chosen to send this week's leftover to the LiberapayOrg account. That will help increase its balance to the amount needed to reimburse me for the renewal of our domain names (https://github.com/liberapay/liberapay.org/issues/10#issuecomment-219282600).

**Comment by MartinDelille** [comment]
I think our first funding goal is to make sure we have a positive balance between our charges and our income. What is the state ?

**Comment by Changaco** [comment]
The only things we currently pay for are the domain names, and we have more than enough income to cover that cost, it's only due to bad timing that the org isn't able to pay me back right now.

**Comment by MartinDelille** [comment]
And the hosting?

**Comment by Changaco** [comment]
liberapay.com is currently hosted on [OpenShift Online](https://openshift.com/) for free. The rest (email, sentry) is on my personal server. It's not ideal but I haven't found an affordable alternative.

We use CloudFlare for our CDN and TLS certificates, it's also free.

**Comment by Changaco** [comment]
I encourage all members of the Liberapay team to read "[3 lessons from Gratipay's take-what-you-want compensation experiment](https://opensource.com/open-organization/16/7/compensating-employees-letting-them-take-what-they-want)".

**Comment by MartinDelille** [comment]
Nice!
Facebook share?

**Comment by Changaco** [comment]
I've sent invitations to @mcl1234 and @jdmansour as they have recently contributed to the translations.

**Comment by Changaco** [comment]
@EliotBerriot has joined the team as a developer.

I've decreased my take once more to make room for him (and other possible newcomers), but our leftover is still zero. @MartinDelille and @Evild67: your nominal takes have been at 2 euros per week for a while, is that amount still what you want to take?

**Comment by Changaco** [comment]
Oh, same question for @KindlyFire. ;-)

**Comment by EliotBerriot** [comment]
Thank you @Changaco, this is very welcoming!

**Comment by MartinDelille** [comment]
I just reduced mine!

**Comment by KindlyFire** [comment]
I'll reduce mine once I get home !

**Comment by Changaco** [comment]
Thanks @MartinDelille and @KindlyFire :-)

We now have a leftover once again!

@EliotBerriot feel free to take a little money. ;-)

**Comment by EliotBerriot** [comment]
I claimed 0.3€ a week, I'll see if I can invest myself regularly on this project :)

**Comment by Evild67** [comment]
Same for me, I just reduced mine.

**Comment by Changaco** [comment]
Well, now we have an excessive leftover. :D

For all the translators here, there is work to do if you're available: https://hosted.weblate.org/projects/liberapay/core/

On that topic, many thanks to @nijel and @revi for their regular contributions to the Czech and Korean translations. :-)

@KindlyFire I noticed that you took your take all the way down to zero, does that mean you won't be contributing again in the near future?

**Comment by KindlyFire** [comment]
Of course I will continue to help translating Liberapay ! It's just that I didn't do anything in a while.

**Comment by taufiqsumadi** [comment]
I have translated some words, I documented in https://github.com/BesutKode/uni-task-1/wiki/taufiqsumadi and i setup nominal takes 0.01 euros per week
just for your information ;)

**Comment by taufiqsumadi** [comment]
whether there is a desire to add a translation into Indonesian?
I might add ind.po into repo, if you like :)

**Comment by Changaco** [comment]
@taufiqsumadi An Indonesian translation is welcome. :-)

**Comment by Changaco** [comment]
I've invited @EdOverflow to join the team, he's been helping improve Liberapay's security.

@EdOverflow Feel free to take a bit of money from the team. :-)

**Comment by Changaco** [comment]
@danielegobbetti has joined the team. He recently improved our Italian translations.

Feel free to [take some money from the team](https://liberapay.com/Liberapay/income/) @danielegobbetti. :-)

**Comment by danielegobbetti** [comment]
@Changaco thanks!
I took the liberty to pipe some money to weblate, hope you don't mind! If it's too much let me know and I'll lower the take!

**Comment by Changaco** [comment]
It's fine. ;-) Note that we do pipe some money to Weblate through LiberapayOrg.

Current org giving is:
- 0.25€ to Aspen
- 0.25€ to Weblate
- 0.10€ to Libravatar

Screenshot:

![spectacle lh8042](https://cloud.githubusercontent.com/assets/1581590/22077344/167b9bda-ddb4-11e6-9fb0-c2cc30682c90.png)

**Comment by Changaco** [comment]
@aggsol has joined the team. He has contributed to the German translation (see #108).

Feel free to take some money from the team @aggsol. ;-)

We have 4 euros of leftover right now.

**Comment by Changaco** [comment]
I've invited @hugoroger to join the team as a translator. (<https://github.com/liberapay/liberapay.com/commit/e12bef43fb83f291eec356a9c4864c09a3b92ed5#commitcomment-20943953>)

Feel free to take some money from the team @hugoroger. ;-)

**Comment by hugoroger** [comment]
haha thanks!

that's so awesome! I didn't know the back-end had such an awesome sharing
feature!

you guys did an awesome job on that platform man!

2017-02-18 10:02 GMT-02:00 Charly C. <notifications@github.com>:

**Comment by Changaco** [comment]
I've invited @jorgesumle to join the team. He's working on the Spanish translation and may also contribute to the code.

Feel free to take some money from the team @jorgesumle.

**Comment by Changaco** [comment]
I've invited @jelv to join the team for his contributions to the Dutch translation.

Feel free to [take some money from the team](https://liberapay.com/Liberapay/income) @jelv.

**Comment by Changaco** [comment]
I've invited @Skybladev2 to join the team, he's done great work on the Russian translation.

Feel free to [take some money from the team](https://liberapay.com/Liberapay/income) @Skybladev2.

**Comment by Changaco** [comment]
I've invited @pskosinski to join the team. The Polish translation is almost complete thanks to him.

Feel free to [take some money from the team](https://liberapay.com/Liberapay/income) @pskosinski.

**Comment by Changaco** [comment]
I've invited https://liberapay.com/LilleTale to join the team as our Norwegian translator.

**Comment by Changaco** [comment]
I've invited @kyrias to join the team as a Swedish translator.

Feel free to [take some money from the team](https://liberapay.com/Liberapay/income) @kyrias.

**Comment by Changaco** [comment]
I've sent an invite to [m4sk1n](https://liberapay.com/m4sk1n) for contributions to the Polish translation.

Welcome to the team @m4sk1n, and please do feel free to take some money. ;-)

**Comment by mkljczk** [comment]
I haven't done that much contribution, I won't take any money… Maybe 
soon… :)

**Comment by Changaco** [comment]
Hey everyone, we currently have a significant leftover of 22 euros, so now is a good time to [adjust you take](https://liberapay.com/Liberapay/income/), especially if you haven't done so in a while.

**Comment by Changaco** [comment]
Also, I've sent an invite to @mattbk.

**Comment by oliverpool** [comment]
@Changaco : you could also significantly increase your share to get closer to your first goal :-)

I just saw that my donation to liberapay does not happen fully and I was a bit confused: maybe note like on the "Lefhover" row of the Income page would be nice. 

This info on hovering an (incomplete) amount in the wallet of the donors would help understanding:
![2017-11-29-134118_1366x768_scrot](https://user-images.githubusercontent.com/3864879/33375692-0a8adc42-d50b-11e7-81c5-cfa5333ac0ba.png)

**Comment by Changaco** [comment]
For the record, several members increased their takes last week, including me.

We need to extend the table with a total of how much each member has taken in the past, maybe divided by the number of weeks. A graph of the history of team takes would also be nice.

**Comment by mattbk** [comment]
A heads up that because of the traffic from disgruntled Patreon users, there is quite a bit left over at the moment (@Changaco should take some of it).

![image](https://user-images.githubusercontent.com/3729038/33848815-73b5fb30-de74-11e7-8aa8-9e27e148c5bc.png)

**Comment by Changaco** [comment]
I can raise my take, but in fact having a second developer would be more useful, because right now we need to speed up development but me getting more money won't help with that since I'm already working full time.

I can only think of two people who are already familiar with how things work and could become core contributors fast: @whit537 and @rohitpaulk. Unfortunately even assuming that Chad would like to work on Liberapay the amount of income we would need for him to be able to do it is unreachable at present. I don't actually know how much Paul would need, but I assume that if he was interested and able to work on Liberapay then he would have joined us already?

**Comment by rohitpaulk** [comment]
> I assume that if he was interested and able to work on Liberapay then he would have joined us already?

I'm interested and following conversations closely, just don't have the time to contribute at the moment :)

**Comment by Changaco** [comment]
I've increased the take of LiberapayOrg from 6.00 to 10.00, and its goal from €10 to €15.

**Comment by Changaco** [comment]
I've sent an invite to [Bisqwit](https://liberapay.com/Bisqwit) for the Finnish translation.

Feel free to [take some money from the team](https://liberapay.com/Liberapay/income) @bisqwit.

**Comment by Changaco** [comment]
Also, a reminder for all translators: you can subscribe on Weblate to receive email notifications when there are new strings to translate.

**Comment by bisqwit** [comment]
Addendum: Just “watching” the translation is not enough (by clicking the eye icon on the project), you have to enable notifications in the subscription settings in your profile if you wish to receive email notifications.

**Comment by MikhailTymchukDX** [comment]
@bisqwit Very good point! I have been missing text changes for several month until I realized that default watch behavior effectively does nothing O_o

**Comment by Changaco** [comment]
I've sent an invite to [Zveryok](https://liberapay.com/Zveryok/), who brought the Ukrainian translation above 50%!

Feel free to [take some money from the team](https://liberapay.com/Liberapay/income) @Zveryok.

**Comment by Changaco** [comment]
This issue is becoming overly long, so I'm closing in favor of a new one: #203.
