### ISSUE TITLE
Password sharing

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#130]
In https://github.com/liberapay/salon/issues/29#issuecomment-297189811 @jorgesumle offered to help with maintaining Liberapay's Diaspora* account. In order to do that we need to set up password sharing. I would like to do it properly, i.e. to be able to see quickly who has access to what, and rotate passwords with minimum effort.

**Comment by Changaco** [comment]
Gratipay has moved from LastPass to 1password: <https://github.com/gratipay/inside.gratipay.com/issues/175>.

**Comment by Zatalyz** [comment]
I use [Teampass](https://github.com/nilsteampassnet/TeamPass) in other project, but it is not critical like Liberapay (no money, no personnal data). 

Tempass work good. A lot of option to generate password, renew, etc. But I can't estimate security in the code.

**Comment by Changaco** [comment]
(Relevant discussion in French: <https://framapiaf.org/@Artanux/99075427570938676>.)

**Comment by Changaco** [comment]
https://bitwarden.com/ looks nice.

**Comment by Changaco** [comment]
I've set up a bitwarden account.

@jorgesumle I'm sending you an invite which should give you access to our Diaspora* password. Let me know if it works and what you think of bitwarden.

**Comment by jorgesumle** [comment]
I've just created an account. It looks good.

What I don't like is that it doesn't work at all without JS and it makes a lot of HTTPS requests to third parties instead of self-hosting the CSS and JS, but I personally don't care too much about that, as I use Tor.

**Comment by Changaco** [comment]
This kind of app can't really run without JS, but you're right that they could at least put a little `<noscript>`.

**Comment by jorgesumle** [comment]
@Changaco, I think you have to accept me or do something. After clicking on the invitation link, I read a message that said that I should wait for admin approval or something similar.

> No collections are being shared with you.

> You do not belong to any organizations.

**Comment by Changaco** [comment]
@jorgesumle Found the "Confirm" button, do you have access now?

**Comment by jorgesumle** [comment]
Yes

**Comment by Changaco** [comment]
I'm adding Bitwarden to the "Thanks" list on the homepage. They fit the criteria: they're open source and they're sponsoring us (50% discount). Commit: https://github.com/liberapay/liberapay.com/commit/739cae2f5d0e1cd49e06830a955f064fb5afbc48
