### ISSUE TITLE
Liberapay's blog sucks

### ISSUE THREAD

**Issue by jorgesumle** [liberapay/salon#136]
Why is Liberapay's blog hosted in Medium? We don't have any control of it and it's not very democratic, I'd say. The ideal thing for me would be a blog in the same domain of Liberapay. For example, https://blog.liberapay.com/. Is that possible?

It's not very difficult to make a blog. As Liberapay uses Python, we could make the blog with Pelican and even have a Git repository for it. What do you think?

With that change and the move to Gitlab, Liberapay would be more libre :)

**Comment by Changaco** [comment]
We have a blog on Medium because I don't want to spend time setting up our own system. I'm more worried about the lack of content in our blog than the software that powers it. The biggest problem with Medium for us is that it's built for English only.

The liberapay.com domain is reserved for the main app, the subdomains are used for languages and receive session cookies. We have liberapay.org that is currently unused, and we could get another domain.

**Comment by jorgesumle** [comment]
I made a quick blog in a few minutes. It uses the theme https://github.com/nairobilug/pelican-alchemy. The Git repo is hosted in [NotABug](https://notabug.org/jorgesumle/liberapay.blog). So... it should be easy from this point to change or customize the theme and include the other article. I know the theme sucks. Screenshots below.

> The biggest problem with Medium for us is that it's built for English only.

With Pelican that won't be a problem. Articles support translations by default. If we want complete subsites we can use the plugin [i18n subsites](https://github.com/getpelican/pelican-plugins/tree/master/i18n_subsites).

![bildschirmfoto vom 2017-05-26 02-18-54](https://cloud.githubusercontent.com/assets/14212780/26475745/e6029930-41b9-11e7-8964-6069ece57b10.png)
---
![bildschirmfoto vom 2017-05-26 02-19-37](https://cloud.githubusercontent.com/assets/14212780/26475746/e89b7fae-41b9-11e7-8c6a-e30c6fc7e368.png)
---
![bildschirmfoto vom 2017-05-26 02-20-16](https://cloud.githubusercontent.com/assets/14212780/26475748/eba006ca-41b9-11e7-9ce4-a3280bcc7643.png)

**Comment by aggsol** [comment]
Setup is normally easy, but updates etc. costs time. We need more useful blogposts.

**Comment by jorgesumle** [comment]
Yes, the lack of posts is another issue. But any opinion of the change from Medium (proprietary, not under our control) to Pelican or another thing? For me it is a bit contradictory that a platform to endorses the commons, uses a proprietary web application.

> Setup is normally easy, but updates etc. costs time. We need more useful blogposts.

Regarding the blogposts, I would recommend also writing some tutorial, tricks, etc., in addition to development updates. Pretty much like the blog of Gitlab. A blog is also a way of showing that the project is alive and keeping in touch with the community, receive feedback from less geeky users, etc.

I propose Pelican because it uses the Jinja2 template lenguage, it's written in Python and it's very flexible (through plugins) and stable.

**Comment by kindlyfire** [comment]
Might I suggest using [Hugo](https://gohugo.io/) ? I'm in vacation now so I can look into making a theme based on what Liberapay currently looks like.

**Comment by tuxayo** [comment]
@jorgesumle 
> The ideal thing for me would be a blog in the same domain of Liberapay. For example, https://blog.liberapay.com/. Is that possible?

Or maybe just have a hosted Ghost instance https://ghost.org/ isn't not critical to self-host everything if the software is libre and hosted by respectable people.

**Comment by kindlyfire** [comment]
I'm willing to host that so that there are no extra server costs. I made a fork of Casper, the default Ghost theme, [kindle-casper](https://code.maly.io/kindlyfire/kindle-casper), that's more pretty to the eye, but can be customized easily. ([preview](https://blog.kindlyfire.me/2018/03/03/configurer-matomo-pour-outrepasser-les-bloqueurs-de-publicite/))

**Comment by Changaco** [comment]
I have no experience with Ghost but it wasn't designed with internationalization in mind so I'm not enthusiastic about it. That said if you can make it work well then I'll be happy to use it.

**Comment by jorgesumle** [comment]
I don't mind as long as it's free software, so I support every option: Hugo, Ghost and Pelican. I suggest making it possible to submit translations easily and manage changes using Git, so that is more transparent.

**Comment by kindlyfire** [comment]
Ghost is pretty much out of the equation. It has localization but not for posts, and it doesn't support Git as a source.

**Comment by Changaco** [comment]
If we go with a static site then [Lektor](https://www.getlektor.com/) may be better than Pelican (or not, there are so many different static site generators that figuring out which one to use is a pain).

However static generators have some limitations/drawbacks, for example contributors who aren't technicians will find them difficult to use. If we're going to have a multilingual blog then we need to make it easy for people to submit post translations.

**Comment by kindlyfire** [comment]
Do we really *have* to be mutli-language ? I guess it is pretty important, but we can set something up in the mean time. Ghost has [a translatable front-end](https://github.com/TryGhost/Ghost/pull/8437) and there is work being done on [multi-lingual content publishing](https://github.com/TryGhost/Ghost/issues/8509).

I suggest setting up a Ghost blog and look further from there.

**Comment by jorgesumle** [comment]
> Do we really have to be mutli-language ?

That's very important for me, English is a big barrier to lots of people. With translations we ensure that the greatest number of people can understand and follow our updates. 

From the multi-lingual Ghost issue:

> Note: If you are interested in leading this project, then please contact us first in slack.

Wow, it looks like they require creating a slack account (proprietary) to discuss and accept a contribution, which makes also the discussion virtually invisible.

> If we go with a static site then Lektor may be better than Pelican (or not, there are so many different static site generators that figuring out which one to use is a pain).

Lektor looks friendlier for non-technical people, it's written in Python and uses Jinja2 (like Liberapay.com), it's free software and we can track the blog changes using Git (transparency and easy rollbacks). We could also use a login system online to allow people administer it, so that they don't have to install it locally, which may be difficult for non-technical people.

**Comment by trebmuh** [comment]
> That's very important for me, English is a big barrier to lots of people. With translations we ensure that the greatest number of people can understand and follow our updates.

Totally +1

**Comment by Changaco** [comment]
<https://writing.exchange/@write_as/99745304992520389>:

> [@Liberapay](https://mastodon.xyz/@Liberapay) Let me know if I can help with anything, if you want another platform that you don't have to maintain (and doesn't arbitrarily remove blogs). Happy to give you custom domains, etc. for free.

**Comment by Changaco** [comment]
https://www.netlifycms.org/ looks interesting as an overlay for a static site generator.

**Comment by Changaco** [comment]
https://mastodon.xyz/@johnonolan/99749144880719916

> Hey team, sorry to hear this happened to you! We'd be happy to give you free credit on Ghost(Pro) and plenty of great support if it would be helpful. Drop me a message any time on john at ghost.org

**Comment by davidak** [comment]
I can recommend [Nikola](https://getnikola.com/). Static site generator written in Python, supports multilingual websites, templates with Mako or Jinja2 and works perfectly with git.

If Python is not important, you should have a look at [Hugo](https://gohugo.io/). It's emerging quickly and has many themes.

**Comment by eldelacajita** [comment]
Hi. I just wanted to support the original post. I'm worried to see so many free/libre projects relying on Medium for their communication.

Edit: If I can help somehow with communication, I'd be glad to do so.

**Comment by jorgesumle** [comment]
> You can find more information in {link3_start}this blog post{link_end}, and as always you can reply to this email if you need help.

The linked blog post from one of our strings is only in English, so translators should specify that it's only in English, but how can they know?

**Comment by jorgesumle** [comment]
> However static generators have some limitations/drawbacks, for example contributors who aren't technicians will find them difficult to use. 

Maybe, but Liberapay is a technical project, and we don't lack advanced users, so I don't see that's a big issue. Websites generator are the most efficient, easy-to-maintain and simplest option for blogs.

> If we're going to have a multilingual blog then we need to make it easy for people to submit post translations.

Since the beginning of the Internet, people have just sent translations via email. They could also open an issue in the issue tracker including the translation; GitLab and GitHub issue trackers have support for links, bold, etc. Any admin can later commit and publish the translation, we should have to review the translations anyway, so this is a great solution.

**Comment by Changaco** [comment]
[Medium is a poor choice for blogging](https://medium.com/@nikitonsky/medium-is-a-poor-choice-for-blogging-bb0048d19133)

**Comment by jorgesumle** [comment]
> However static generators have some limitations/drawbacks, for example contributors who aren't technicians will find them difficult to use. If we're going to have a multilingual blog then we need to make it easy for people to submit post translations.

If we create a `.po` file for each post, translators will be able to use Weblate. I found a [project to create `.po` files from Markdown](https://github.com/mondeja/mdpo). I'm experienced with Pelican, and I think I could finish the work in a few days.

**Comment by Changaco** [comment]
I've pretty much given up on the idea of setting up a separate blog. Instead I would like to finish the work on <https://github.com/liberapay/liberapay.com/issues/41>, so that Liberapay's blog will be on Liberapay.

**Comment by jorgesumle** [comment]
You're right. With that feature there would be no need for a separate blog, so I'm closing this.
