### ISSUE TITLE
Mastodon archive

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#142]
Some francophone Mastodon users have created a small bad buzz around our policy of neutrality. This issue is to keep a record, and possibly discuss the matter. It all started a week ago with a calm discussion about Liberapay's rules:

https://mastodon.potager.org/@lunar/41459

A few days later the same user started the bad buzz:

https://mastodon.potager.org/@lunar/47812

Then others followed:

https://witches.town/@szam/2474423
https://witches.town/@Kamillion/2512150
https://mastodon.opportunis.me/@lila_bliblu/487599

**Comment by Changaco** [comment]
https://mstdn.nl/@poujolrost/265138

**Comment by Changaco** [comment]
On the other hand I'm happy to report that one person sent us a positive message yesterday: <https://social.targaryen.house/@jp_dufraigne/3304391>. That was nice. 🙂

**Comment by Zatalyz** [comment]
I'm not sure that it's a really bad buzz, but a good time to explain our neutrality. I work to write a blog article, I give you a pad tomorrow.

Mastodon is not the good media for a argumented discussion. Here, people don't understand how Liberapay work (why "project" ? We have people in Liberapay, project is accessory), and arguments are poor, confused, poorly ordered (and for us too), but it is normal : too short to write good things. Mastodon is like Twitter : good for information, not for discussion. This controversy is a perfect example : all people (me, you, others) follows a monologue. For next time, I think it is good idea to redirect quickly to a media where a neat discussion can be exist : here, Diaspora... (no character limitation number, discuss flat if possible).

**Comment by Changaco** [comment]
At this point I think answering would only make things worse.

**Comment by Changaco** [comment]
https://witches.town/@Kapouf/4321312

**Comment by aggsol** [comment]
Good response.

**Comment by Changaco** [comment]
https://witches.town/@Alda/4934729
