### ISSUE TITLE
Understanding excessive adding of money.

### ISSUE THREAD

**Issue by aggsol** [liberapay/salon#167]
While translating I found this text:

_We don't allow adding money when your donations are already funded by your income. If this is a problem for you please send an email to support@liberapay.com explaining why._

When does that actually happen? If having more income than donating? So one has to donate more to be able to add money to the wallet?

**Comment by revi** [comment]
If I understand correctly, if your income > your donation , you cannot do payin, and that messages are shown. So yes, if you want to add money to your wallet via credit card/bank wire/etc, you need to donate more than you get donated.

**Comment by Changaco** [comment]
The reason why we disallow payins when donations are already covered by income is that in this case adding money is pointless: it will only sit in your wallet until you withdraw it back, and you'll have lost some of it in the process because of payin fees.
