### ISSUE TITLE
The end of Gratipay

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#168]
See <https://github.com/gratipay/inside.gratipay.com/issues/1196>.

This issue is about the consequences of Gratipay's shutdown on Liberapay.

**Comment by Changaco** [comment]
First thoughts:

- We still use one library that is under the Gratipay org on GitHub: [postgres.py](https://github.com/gratipay/postgres.py).
- The disappearance of Gratipay's HackerOne program would increase the pressure for <https://github.com/liberapay/liberapay.com/issues/549>.

**Comment by revi** [comment]
That's sad news, feeling like some sort of end of era. :(

**Comment by Changaco** [comment]
Further thoughts:

- Liberapay has never had anything like [inside.gratipay.com](http://inside.gratipay.com/), is there some stuff in there we want to salvage?
- What of <https://github.com/AspenWeb>? It's been stagnating for a while, and with Gratipay gone it'll be even less used than it is now.

**Comment by aggsol** [comment]
* I see nothing worthwhile from inside.gratipay.com we would want
* Just for what every is required by Liberapay. Closing aspen.io seems to be the logical next step.

**Comment by Changaco** [comment]
https://gratipay.news/the-end-cbfba8f50981

**Comment by EdOverflow** [comment]
> What of https://github.com/AspenWeb? It's been stagnating for a while, and with Gratipay gone it'll be even less used than it is now.

@Changaco: Please keep in mind that AspenWeb currently has a vulnerability disclosure program on HackerOne (https://hackerone.com/aspen).

**Comment by Changaco** [comment]
@EdOverflow Okay, but I'm not sure what you're trying to say by reminding me of that.

**Comment by EdOverflow** [comment]
@Changaco: If you want to close aspen.io we need to contact HackerOne support in order to go through the whole process of closing down AspenWeb's VDP.

**Comment by Changaco** [comment]
Actually I didn't mean to suggest abandoning Aspen, I was merely wondering "out loud" if the shutdown of Gratipay could lead to that.

**Comment by mattbk** [comment]
I rather like inside.gratipay.com as a place to keep information for contributors. /see-also is a good list, unless there is a better one somewhere.

Aspen the framework isn't needed, or just the website promoting it?

**Comment by Changaco** [comment]
> /see-also is a good list, unless there is a better one somewhere.

We link to <https://wiki.snowdrift.coop/market-research/other-crowdfunding> in our FAQ.

> Aspen the framework isn't needed, or just the website promoting it?

We still use Aspen+Pando, and as long as we do we'll keep maintaining them, including their documentation on aspen.io.
