### ISSUE TITLE
How is identity handled for users claiming a pledge?

### ISSUE THREAD

**Issue by jibe-b** [liberapay/salon#174]
Pledges are linked to a pointer.

How is the identity of the person claiming for pledges checked?

**Comment by Changaco** [comment]
A pledge is linked to an account on another platform like GitHub or Twitter, to claim it the person has to prove that they control this external account, by connecting it to their Liberapay account. The process is fully automated.

**Comment by jibe-b** [comment]
Thanks @Changaco . So if I understand well, it's done with OpenID connect.

**Comment by Changaco** [comment]
Not exactly, it's platform-specific OAuth.

**Comment by jibe-b** [comment]
ok that's enough for me.
