### ISSUE TITLE
Using Mangopay to pay for services (e.g. hosting/VPS)

### ISSUE THREAD

**Issue by danielegobbetti** [liberapay/salon#178]
Hello all!

We are using liberapay with gadgetbridge quite successfully. Thanks! Our team is wondering whether Mangopay could be used to directly pay for e.g renting a VPS by some provider in europe, without the need to take the money out to a personal bank account and then paying from there.

Thanks in advance!

**Comment by Changaco** [comment]
It's not possible to pay from a Mangopay wallet directly.

For shared costs like servers and domain names I've built a system to reimburse the person who pays the bill (<https://github.com/liberapay/liberapay.com/issues/505>), however it's not finished yet.

**Comment by danielegobbetti** [comment]
Thanks a lot @Changaco !

In any case the issue you linked would not apply to us, as we are only a team and no organization.

**Comment by Changaco** [comment]
@danielegobbetti The reimbursement system will probably be available to teams someday (related issues: <https://github.com/liberapay/liberapay.com/issues/753> and <https://github.com/liberapay/liberapay.com/issues/803>).
