### ISSUE TITLE
Who are patrons, actually?

### ISSUE THREAD

**Issue by Skybladev2** [liberapay/salon#179]
Hi,

I noticed 5 patrons at my profile when navigating [Game Development community](https://en.liberapay.com/for/Game_Development/):
![default](https://user-images.githubusercontent.com/548735/33038977-7be6605c-ce47-11e7-8aab-9d5b0f2b6404.png)

I don't understand, who are they? Why 5?

I know donations are anonymous. I mean what "patron" means here?
I receive money only as a member of [Liberapay team](https://en.liberapay.com/Liberapay/). That's my only income, so a patron can not be a donator, right?

**Comment by mattbk** [comment]
Liberapay works by passing through donations. So your take from https://en.liberapay.com/Liberapay/income/ is 3.00, which is made up of donations from donors to Liberapay. This gets around treating Liberapay (or any team) as a legal entity, because no money is held in escrow for the team itself.

So to answer the question, yes, "patrons" are "donors."

**Comment by mattbk** [comment]
See this note on the takes page (example from one of my teams):

![image](https://user-images.githubusercontent.com/3729038/33041300-7a52a2e4-ce03-11e7-89a1-325056887b28.png)

**Comment by Changaco** [comment]
The "Patrons" number (`npatrons` in the code) is basically how many donors you'll receive money from in the next payday (if nothing changes before then). Obviously it's also often the same number of people you received money from during the last payday.

**Comment by Skybladev2** [comment]
So, 200 patrons of Liberapay are organized in queue and then engine starts to take money from each of them: N1 euros from the first, N2 from the second and so on.
When engine finishes collecting the take for any team member, it counts how many patrons gave their money to this particular member and shows it as a patron count?
Hence, this number can vary even if the goal is unchanged?

**Comment by mattbk** [comment]
Correct. More detail: https://github.com/liberapay/liberapay.com/blob/f926ed8b79e823af0f0fafaad0ec4c154816530a/liberapay/billing/payday.py#L357

**Comment by Skybladev2** [comment]
Cool, thanks!
