### ISSUE TITLE
[Feature Request] payday notification on diaspora

### ISSUE THREAD

**Issue by trebmuh** [liberapay/salon#182]
I'd like to suggest to publish a payday notification on diaspora as [done for mastodon/twitter ](https://github.com/liberapay/salon/issues/181#issuecomment-347871525). I'd love to be able to one-click share it on my diaspora account.

**Comment by Changaco** [comment]
Diaspora isn't really a micro-blogging platform like Mastodon and Twitter, I tend to treat it more like Facebook: I only post recaps and big news.
