### ISSUE TITLE
News - December 2017

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#183]
This is Liberapay's news thread, its purpose is to help us achieve #29.

cc @liberapay/media-managers

**Comment by Changaco** [comment]
https://mastodon.rocks/@Liberapay/99098685852283424
https://twitter.com/liberapaye/status/936550494570414080

> Good news: our payment processor has lowered their pricing on direct debit payments, so from now on you will pay a €0.59 fee per debit instead of €0.94!

**Comment by Changaco** [comment]
https://mastodon.rocks/@Liberapay/99099796917397887
https://twitter.com/liberapaye/status/936620898483949571

> Reminder: Gratipay is shutting down at the end of the month! If you had an account there you can migrate it: simply open https://gratipay.com/, log in, and click the "Migrate to Liberapay" button.

**Comment by Changaco** [comment]
https://mastodon.rocks/@Liberapay/99109686486477834
https://twitter.com/liberapaye/status/937254321011548160

> You may have noticed that https://liberapay.com/ was slower than usual in the past month. This performance issue has now been fixed.

**Comment by Changaco** [comment]
https://mastodon.rocks/@Liberapay/99129779631317738
https://twitter.com/liberapaye/status/938540957498269696

> Now seems like a good time to remind everyone that our platform is designed to help you avoid wasting money in excessive payment processing fees.

**Comment by Changaco** [comment]
https://mastodon.rocks/@Liberapay/99134205529613505
https://twitter.com/liberapaye/status/938823341728780290

> Liberapay is now officially a multi-currency platform! We have implemented support for US dollars in addition to the euro. Blog post: https://medium.com/liberapay-blog/liberapay-now-supports-us-dollars-f9484e3008f8

**Comment by Changaco** [comment]
(If you share the blog post on HN or Reddit or whatever don't forget to post the link here.)

**Comment by tuxayo** [comment]
Thanks for these news. A monthly thread like this one is a great idea.

**Comment by Changaco** [comment]
https://framasphere.org/posts/4290610

> ### Liberapay now supports US dollars
>
> Liberapay is now officially a multi-currency platform! We have implemented support for US dollars in addition to the euro. Blog post: https://medium.com/liberapay-blog/liberapay-now-supports-us-dollars-f9484e3008f8
>
> #### Other news since our last post
>
> - Bank wires can now be properly canceled if you change your mind about using this payment method.
> - Our payment processor lowered their pricing on direct debit payments, so they now cost you €0.59 per debit instead of €0.94.
> - A tool to migrate Gratipay accounts to Liberapay was created since the former is [shutting down](https://gratipay.news/the-end-cbfba8f50981) at the end of the year.
> - The new profile page style was deployed a while ago, as well as improved user lists. You should [complete your profile](https://liberapay.com/about/me/edit) with a short description if you haven't done it yet.
> - Metadata was added to Liberapay profiles so that links posted on social networks created nice boxes showing avatar+title+description.
> - The possibility to change the name of a team was implemented.
> - We also implemented the creation of a redirection when an account's name (and thus its URL) is modified.
> - We put in place some rate limits to hinder spam and denial-of-service attacks.
> - As usual lots of small improvements and bugfixes.
>
> #Liberapay #i18n #Currencies #USD #Donations #Crowdfunding #Micropayments #en

**Comment by trebmuh** [comment]
Traduction en français / French translation : https://framasphere.org/posts/4318985

> # Liberapay prend maintenant en charge les dollars américains
> 
> Liberapay est maintenant officiellement une plateforme multi-devise ! Nous avons ajouté la possibilité d’utiliser le dollar américain en plus de l’euro. Billet de blog (en anglais) : https://medium.com/liberapay-blog/liberapay-now-supports-us-dollars-f9484e3008f8 .
>##  Autres nouveautés depuis notre dernier billet :
> 
> - Les virements bancaires peuvent maintenant être annulés convenablement si vous changez d’idée à propos de l’utilisation de cette méthode de paiement.
> - Notre service de traitement des paiements a réduit ses tarifs pour les paiements par prélèvement automatique. Ainsi le coût est maintenant de 0,59 € par débit au lieu de 0,94 €.
> - Un outil pour migrer les comptes Gratipay vers #Liberapay a été créé puisque Gratipay va fermer à la fin de l’année.
> - Un nouveau style de page de profil a été déployé depuis un certain temps, ainsi que des listes améliorées d’utilisateurs. Vous devriez compléter votre profil avec une brève description si vous ne l’avez pas encore fait.
> - Des métadonnées ont été ajoutées aux profils Liberapay afin que les liens postés sur les réseaux sociaux créent de jolies boîtes affichant avatar+titre+description.
> - La possibilité de changer le nom d’une équipe a été mise en place.
> - Nous avons également mis en œuvre la création d’une redirection lorsque le nom d’un compte (et donc son URL) est modifié.
> - Nous avons mis en place certaines limitations pour empêcher le spam et les attaques par déni de service.
> - Comme d’habitude, beaucoup de petites améliorations et corrections de bogues.
> 
> #i18n #Devises #USD #Dons #FinancementParticipatif #Micropaiements #PrixLibre #Communs #french #fr

**Comment by trebmuh** [comment]
It was my first one and I'm just seeing that I forgot 2 links in the text. Since one can't edit his post in Diaspora*, I added the 2 missing links in an self-answer to the post.

Hope that's fine since I thought that it'd be better than removing the original post and redoing it.

I'll spin my fingers seven times on my keyboard before pressing the Share button next time!

**Comment by Changaco** [comment]
Thanks @trebmuh! Details for next time:

- the title levels should be the same in the translation as in the original message
- for "US dollar" we use "dollar états-unien"
- for "payment processor" we use "opérateur de paiement"
- for "direct debit" we use "prélèvement bancaire"

**Comment by trebmuh** [comment]
Thanks for the comment @Changaco , keep telling me how to improve and to stick with the general movement.

I've tried to create a wiki page in this repo to put your remarks above + [those guideline basics](https://github.com/liberapay/salon/issues/29#issuecomment-219011393) + what you told me on IRC:

> en gros sur Diaspora* on ne poste quasiment que des résumés, alors que Mastodon c'est à peu près comme Twitter on met les news au fur et à mesure

but it looks not to be allowed to create a wiki page here. Shall I then add those to the README.md (I don't think so) or would you have a better idea? The general idea here is to have a general guidelines document for the "media-managers" (if that's how we are named).

By the way, I saw that the Diaspora* account biography is only in English. I'd recommend to add a French bio as well since we're posting in French as well (consistency) and since the French and francophone community looks to be a big part of what Liberapay is so far. Shouldn't we?


**Edit:** done 18 hours later, see https://github.com/liberapay/salon/issues/187

**Comment by jorgesumle** [comment]
> * for "US dollar" we use "dollar états-unien"
> * for "payment processor" we use "opérateur de paiement"
> * for "direct debit" we use "prélèvement bancaire"

Can any French translator add those words to the Weblate glossary for the French translation, and add other conventions used? Right now the French translation glossary is empty: https://hosted.weblate.org/dictionaries/liberapay/fr/

The translation glossary can be very useful for new translators.

**Comment by tuxayo** [comment]
> Can any French translator add those words to the Weblate glossary for the French translation

Done (those 3)

**Comment by Changaco** [comment]
https://mastodon.rocks/@Liberapay/99194900072748294

> We've started using the open source password manager https://bitwarden.com/ to share credentials within our team.
>
> Thanks to the Mastodon users who suggested this in a previous discussion, and to Bitwarden for sponsoring our use of their service!

https://twitter.com/liberapaye/status/942708661037797377

**Comment by Changaco** [comment]
https://mastodon.rocks/@Liberapay/99256981973348830
https://twitter.com/liberapaye/status/946681853959958528

> Current internationalization status of liberapay.com: it's fully available in 12 languages and supports 2 currencies.
>
> You can help us do even better by contributing to the translations yourself on https://hosted.weblate.org/projects/liberapay/core/ and by supporting the team financially through https://liberapay.com/Liberapay/donate
>
> ![weblate-liberapay-core-2017-12-29](https://user-images.githubusercontent.com/1581590/34434502-eafeae7e-ec86-11e7-9753-6ccf960c891a.png)

**Comment by Changaco** [comment]
https://twitter.com/liberapaye/status/946716033729138693

> This is it folks, if you haven't migrated your Gratipay account yet you should do it now!
>
> 1) Open https://gratipay.com/
> 2) Log in
> 3) Click the "Migrate to Liberapay" button
> 4) Read the page on Liberapay and confirm the migration
>
> https://twitter.com/Gratipay/status/946521022832013313

https://mastodon.rocks/@Liberapay/99257546745974992

**Comment by trebmuh** [comment]
[Mastodon] Published a translation of the last one : https://mastodon.rocks/@Liberapay/99257990727203171
