### ISSUE TITLE
Watercooler - Q1 2018

### ISSUE THREAD

**Issue by trebmuh** [liberapay/salon#192]
This is Liberapay's quarterly "what's up?" thread. Previous: https://github.com/liberapay/salon/issues/164.

**Comment by trebmuh** [comment]
https://orrery.prismaticmedia.com/2017/12/29/patreoff/

**Comment by Changaco** [comment]
Our main Mastodon account is malfunctioning again (new toots and notifications aren't arriving).

**Comment by trebmuh** [comment]
@Changaco : could that be because I was connected to it maybe? (I just disconnected before writing this)

**Comment by Changaco** [comment]
No.

**Comment by Changaco** [comment]
[Free software developers on Liberapay](https://www.reddit.com/r/linux/comments/7qihgn/free_software_developers_on_liberapay/)

**Comment by Changaco** [comment]
[Fee breakdown for various donation platforms (Fosspay v Liberapay v Patreon) ⋅ /r/linux](https://www.reddit.com/r/linux/comments/7r9ke6/fee_breakdown_for_various_donation_platforms/)

**Comment by Changaco** [comment]
[fr] [Création de contenu et financement en 2018 – Blog à part](https://alias.erdorin.org/creation-de-contenu-financement-2018/)

**Comment by Changaco** [comment]
Suspended one account on suspicion of card fraud.

**Comment by jorgesumle** [comment]
[Extensions in Firefox 59](https://blog.mozilla.org/addons/2018/01/26/extensions-firefox-59/)

**Comment by Changaco** [comment]
Flattr: [Our extension is now open source!](https://blog.flattr.com/2018/01/flattr-open-source/)

https://github.com/flattr/flattr-extension

**Comment by Changaco** [comment]
[Cloudflare Workers is now on Open Beta](https://blog.cloudflare.com/cloudflare-workers-is-now-on-open-beta/)

Related issue: <https://github.com/liberapay/liberapay.com/issues/360>.

**Comment by Changaco** [comment]
[Send Year-end Tax Receipts to All Your Donors](https://donorbox.org/nonprofit-blog/send-year-end-tax-receipts-donors/) (Donorbox)

**Comment by Changaco** [comment]
[Two holiday stories](https://joeyh.name/blog/entry/two_holiday_stories/) - A nice blog post I missed during the Patreon fiasco.

**Comment by Changaco** [comment]
[Flattr fees 101](https://blog.flattr.com/2018/02/flattr-fees/)

> We’re pleased to officially announce that Flattr is currently **completely free to use for all**. To really grow Flattr into a solution that makes both creators and contributors happy, we know that initially we should bare [sic] some costs to make this happen, so with this said, we’re committing to incur all the processing and payment fees so that it’s completely free for you to use.

**Comment by Changaco** [comment]
[Updates feature and a new design are live!](https://mailchi.mp/opencollective/200k-for-open-sourceachievement-unlocked-1078201) - Open Collective

**Comment by Changaco** [comment]
[January 2018 Investors update – Open Collective](https://medium.com/open-collective/january-2018-investors-update-b9b23798ba4d)

**Comment by Changaco** [comment]
[Ending Bitcoin support](https://stripe.com/blog/ending-bitcoin-support) - Stripe

**Comment by Changaco** [comment]
[Block Fraudulent Test Donations](https://donorbox.org/nonprofit-blog/block-fraudulent-test-donations/) - Donorbox

**Comment by Changaco** [comment]
[The path to sustainably working on FOSS full-time | Drew DeVault’s Blog](https://sircmpwn.github.io/2018/02/24/The-road-to-sustainable-FOSS.html)

**Comment by Changaco** [comment]
[New release: Piranha | MANGOPAY API Docs](https://docs.mangopay.com/blog/new-release-piranha)

> ### New functionality included in this release
>
> - Great news for our clients operation in the UK and US. We are now able to give you an AVS (Address Verification System) score by card transaction. AVS compares the billing address of the transaction with the registered address of the card holder. This strong anti-fraud tool requires few changes with additional parameter to send us. Please find [here](https://docs.mangopay.com/guide/avs) a little set-up guide.
> - When doing a 3DS authentication, users receive a text message on his mobile phone which needs to be enter on the authentication page. We are now able to bring more transparency by displaying your name (Client.name) both on the sms message and on the authentication page.
> - As of last release, we are continuously improving the card fingerprint feature by bringing a new list to find every preauths done with a same unique card.

**Comment by Changaco** [comment]
https://mastodon.rocks/@Liberapay/99631594400738724
https://twitter.com/liberapay/status/970656835647746048

> https://liberapay.com/ can now check your password and warn you if it appears in Troy Hunt's database of 500 million leaked passwords (see https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/ for details on this database).
>
> This is done automatically when you change your password, or when you log in with your password and it hasn't been checked in the last 6 months.
>
> ![screenshot of a warning notification shown after a user logged in with a weak common password](https://user-images.githubusercontent.com/1581590/36937121-ec74316a-1f0e-11e8-9d1e-811d58f7f86d.png)

**Comment by Changaco** [comment]
https://twitter.com/Changaco/status/971672229321805824

> Ça y est, je reçois désormais l'équivalent d'un petit #RevenuDeBase pour mon travail sur @.liberapay et autres projets libres ! Un grand merci à tous mes donateurs ! Prochaine étape : un SMIC.
>
> Me soutenir : https://fr.liberapay.com/Changaco
> Soutenir Liberapay : https://fr.liberapay.com/Liberapay
>
> ![capture d'écran du "bandeau" de ma page de profil qui montre que j'ai atteint mon premier objectif](https://user-images.githubusercontent.com/1581590/37142378-3229ff80-22b8-11e8-8dcf-bc308e287d2c.png)

**Comment by Changaco** [comment]
https://mastodon.cloud/@Changaco/99647565315471663

**Comment by Changaco** [comment]
https://framasphere.org/posts/4698592

**Comment by Changaco** [comment]
[F-Droid now supports Liberapay](https://f-droid.org/2018/03/02/liberapay-support.html)

**Comment by Changaco** [comment]
[Everyone can now run JavaScript on Cloudflare with Workers](https://blog.cloudflare.com/cloudflare-workers-unleashed/)

Pricing: $0.50 per month per million requests, with a $5 monthly minimum covering 10 million requests.

**Comment by Changaco** [comment]
Our primary Mastodon account is completely lost.

> The 16/03/2018, during the update to Mastodon v2.3.1, this instance has crashed and lost all accounts, media and toots. I'm totally sorry for all users. It just a fucking nightmare...

![screenshot_20180316_143158](https://user-images.githubusercontent.com/1581590/37523290-c90e7ccc-2926-11e8-8637-681d20f59173.png)

**Comment by trebmuh** [comment]
Oh shit! :-/

**Comment by kindlyfire** [comment]
Rip backups, if there even were any

**Comment by kindlyfire** [comment]
We can transform the secondary account into the primary one and create a backup account again ? Then post something explaining the change. I run [my own instance](https://maly.io) if you want (runs on a pretty beefy machine)

**Comment by Changaco** [comment]
Already done.

https://mastodon.xyz/@Liberapay/99694111285023482

> Our old Mastodon account is dead. Please follow this one instead, as well as our new alt account [@Liberapay@mstdn.io](https://mstdn.io/@Liberapay).
>
> RIP https://mastodon.rocks/@Liberapay

**Comment by trebmuh** [comment]
French translation : https://mastodon.xyz/@Liberapay/99694821063795287

**Comment by Changaco** [comment]
I've retrieved from Google's cache two pages of the list of Mastodon accounts we were following, and started following them from our new account.

**Comment by revi** [comment]
To prevent such bad thing affecting us, maybe we should export data regularly ($mastodon_url/settings/export seem to have "You follow" table in csv.)

**Comment by Changaco** [comment]
Someone pointed an HTTP scanner at da.liberapay.com. They used Tor to hide.

```
select * from rate_limiting where ts >= '2018-03-17 14:00:00' order by ts;
                  key                  | counter |              ts               
---------------------------------------+---------+-------------------------------
 ...
 add_email.source:34628                |       1 | 2018-03-17 14:49:53.673391+00
 add_email.target:sample@email.tst     |       2 | 2018-03-17 14:49:53.764993+00
 add_email.source:34629                |       1 | 2018-03-17 14:49:53.767659+00
 sign-up.ip-addr:77.247.181.162        |       5 | 2018-03-17 14:49:55.089199+00
 sign-up.ip-net:77.247                 |       5 | 2018-03-17 14:49:55.092264+00
 sign-up.ip-addr:23.129.64.102         |       5 | 2018-03-17 14:51:24.782915+00
 sign-up.ip-net:23.129                 |       5 | 2018-03-17 14:51:24.785225+00
 sign-up.ip-addr:176.126.252.11        |       5 | 2018-03-17 14:52:20.407804+00
 sign-up.ip-net:176.126                |       5 | 2018-03-17 14:52:20.409995+00
 sign-up.ip-version:4                  |      15 | 2018-03-17 14:52:33.019539+00
 sign-up.ip-addr:178.17.170.196        |       4 | 2018-03-17 14:52:35.801775+00
 sign-up.ip-net:178.17                 |       4 | 2018-03-17 14:52:35.804325+00
 sign-up.ip-addr:65.19.167.130         |       3 | 2018-03-17 14:52:45.49881+00
 sign-up.ip-net:65.19                  |       3 | 2018-03-17 14:52:45.501251+00
 sign-up.ip-addr:185.38.14.171         |       3 | 2018-03-17 14:52:51.264668+00
 sign-up.ip-net:185.38                 |       3 | 2018-03-17 14:52:51.267178+00
 sign-up.ip-addr:192.42.116.13         |       5 | 2018-03-17 14:53:20.954052+00
 sign-up.ip-net:192.42                 |       5 | 2018-03-17 14:53:20.956788+00
 sign-up.ip-addr:66.70.217.179         |       2 | 2018-03-17 14:53:25.803805+00
 sign-up.ip-net:66.70                  |       2 | 2018-03-17 14:53:25.806318+00
 ...
```

**Comment by Changaco** [comment]
Our Medium account and all its posts have been blocked for bogus reasons. https://medium.com/@liberapay

My email to Medium support:

> We neither use nor write about crypto currencies, so I request that you restore our account immediately.
>
> Blocking access to accounts and published stories for bogus reasons is unacceptable behavior, you can expect repercussions.

**Comment by trebmuh** [comment]
Did you received an explanation about _why_ they blocked it?

**Edit:** answer here https://mastodon.xyz/@Liberapay/99744414079487371

**Comment by jorgesumle** [comment]
> We don't accept cryptocurrencies [...]

There was this text, I can read from the Spanish translation («No aceptamos criptomonedas, y no pensamos cambiar eso en un futuro próximo.»). I didn't know they censored people for talking about cryptocurrencies.

I think it's a good time to solve #136

**Comment by Changaco** [comment]
https://mastodon.xyz/@Liberapay/99744324870271197
https://twitter.com/liberapay/status/977872191797841920

> Today's lesson: Medium is bad. They've suspended our account and blocked access to all our published stories for bogus reasons and with only 12 hours notice.
>
> ![Screenshot of the message shown to visitors of our Medium account. Text: “This page is unavailable. Browse for great reads on Medium.”](https://6-28.mastodon.xyz/media_attachments/files/001/732/517/original/a815fc44f8d80a4c.png)

**Comment by jorgesumle** [comment]
**Spanish translation**

Lección del día: Medium es malo. Han suspendido nuestra cuenta y bloqueado el acceso a todas nuestras historias publicadas por razones falsas y con un aviso de solo 12 horas.

@liberapay/media-managers, can you publish https://github.com/liberapay/salon/issues/208#issuecomment-375943159 and this translation? Right now, I only have a Diaspora* password.

**Comment by trebmuh** [comment]
In French on Mastodon: https://mastodon.xyz/@Liberapay/99744506201672777

**Comment by Changaco** [comment]
@jorgesumle I've added you to the Mastodon group, you should have access to the passwords of our accounts now.

**Comment by Changaco** [comment]
I've improved [Liberapay's Wikipedia page](https://en.wikipedia.org/wiki/Liberapay) a bit.

**Comment by Changaco** [comment]
https://news.ycombinator.com/item?id=16672203

**Comment by Changaco** [comment]
Response from Medium's support:

> Thank you. We have reviewed your account, and it is now reinstated.

**Comment by Changaco** [comment]
https://mastodon.xyz/@Liberapay/99745922397657868

> Our Medium account has been reinstated.
>
> Thanks to everyone who offered to help with hosting our blog elsewhere. We were already planning to set up our own thing for various reasons (including Medium's complete lack of support for translations). Of course we'll toot a link to our new blog as soon as it's up.

https://twitter.com/liberapay/status/977976301914021888

**Comment by trebmuh** [comment]
In French on Mastodon : https://mastodon.xyz/@Liberapay/99746277545464741

**Comment by jorgesumle** [comment]
In Spanish on Mastodon: https://mastodon.xyz/@Liberapay/99746410286716397

**Comment by Changaco** [comment]
https://mastodon.xyz/@Liberapay/99749448303038891

> Special thanks to the following cool folks whose answers to our toot about Medium were offers to help us: [@write_as](https://writing.exchange/@write_as) [@johnonolan](https://mastodon.xyz/@johnonolan) [@lord](https://octodon.social/@lord) [@sheogorath](https://g0v.social/@sheogorath).

**Comment by trebmuh** [comment]
On Mastodon in French: https://mastodon.xyz/@Liberapay/99750073381440720

**Comment by jorgesumle** [comment]
On Mastodon in Spanish: https://mastodon.xyz/@Liberapay/99751075182123150

**Comment by Changaco** [comment]
@jorgesumle I deleted that because two of the mentions were broken. The toot doesn't make much sense if it doesn't actually link to the people we're thanking.

Copy:

> Damos las gracias sinceramente a las siguientes geniales personas cuyas respuestas a nuestro toot sobre Medium fueron ofertas para ayudarnos: `@write_as @johnonolan @lord @sheogorath`.

**Comment by Changaco** [comment]
https://www.facebook.com/Liberapay/posts/959091627582578

> In case some of you are trying to #DeleteFacebook, here's a reminder: we're also on Diaspora* (https://framasphere.org/u/liberapay), Mastodon (https://mastodon.xyz/@Liberapay), Twitter (https://twitter.com/liberapay), and Medium (https://medium.com/liberapay-blog).

**Comment by Changaco** [comment]
I've created a ["JavaScript" label](https://github.com/liberapay/liberapay.com/labels/JavaScript) so that potential contributors can easily find issues related to JavaScript code.

**Comment by Changaco** [comment]
https://mastodon.xyz/@Liberapay/99761400653752838

> [@Jelv](https://mastodon.social/@Jelv) [@geekonaut](https://mastodon.social/@geekonaut) It would indeed be great to see other developers join our team. However right now our income is still too low to pay even one person to work full time on Liberapay, so we're looking for contributors who can afford to work on a project that doesn't pay their bills, or people who live in areas where €400/month is a decent amount of money.

**Comment by trebmuh** [comment]
_(no need for a French translation for this one)_
