### ISSUE TITLE
News - January + February 2018

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#193]
This is Liberapay's news thread, its purpose is to help us achieve #29.

cc @liberapay/media-managers

**Comment by Changaco** [comment]
https://mastodon.rocks/@Liberapay/99285291249721918

> Reminder: 3 months ago we started asking for a short description in addition to your full profile statement, but many are still missing today. For example the Mastodon team doesn't have one, as you can see in the attached screenshot. The new year is a good time to update and complete your profile: https://liberapay.com/about/me/edit
> ![Screenshot showing the top 3 teams on Liberapay](https://mastodon.rocks/system/media_attachments/files/000/338/631/original/60f77c7e00336d9a.png)

**Comment by Changaco** [comment]
https://twitter.com/liberapaye/status/948494033118220289

**Comment by trebmuh** [comment]
French translation on Mastodon : https://mastodon.rocks/@Liberapay/99286166291606885

(I changed from Mastodon to Parabola because Mastodon did it)

**Comment by Changaco** [comment]
https://twitter.com/liberapaye/status/949597226346696704

> Our main account has been renamed to @.liberapay.

https://mastodon.rocks/@Liberapay/99302748732494630

> Our main birdsite account has finally been renamed from @.liberapaye to @.liberapay, almost two years after we first asked Twitter to reallocate this username to us. https://twitter.com/liberapay

**Comment by trebmuh** [comment]
On Mastodon in French : https://mastodon.rocks/@Liberapay/99303372210019029

**Comment by Changaco** [comment]
https://mastodon.rocks/@Liberapay/99410614270098880
https://twitter.com/liberapay/status/956513733253230592

> We've identified the source of the silent failures when using Liberapay through some browsers like Chrome. A bypass has been put in place.
>
> Technical details: https://github.com/liberapay/liberapay.com/issues/952

**Comment by trebmuh** [comment]
https://mastodon.rocks/@Liberapay/99411231528384146
(French translation)

> Nous avons identifié la source d'erreurs silencieuses lors de l'utilisation de Liberapay avec certains navigateurs comme Chrome. Un contournement a été mis en place.
> 
> Détails techniques : https://mastodon.rocks/@Liberapay/99411239048206457

**Comment by Changaco** [comment]
Draft blog post for Liberapay's second anniversary: https://medium.com/@liberapay/the-second-year-of-liberapay-c017b73c9721

**Comment by Changaco** [comment]
Draft updated. Planning to publish in about an hour.

**Comment by trebmuh** [comment]
Nice and full of information. From the top of my head, all the important 2017 info are summarized in the draft. Well done.

**Comment by Changaco** [comment]
https://twitter.com/liberapay/status/959757217347112961
https://mastodon.rocks/@Liberapay/99461299146497641

> Today is the second anniversary of Liberapay's launch! Blog post: https://medium.com/@liberapay/the-second-year-of-liberapay-c017b73c9721

**Comment by Changaco** [comment]
https://framasphere.org/posts/4549395

> ### Today is the second anniversary of Liberapay's launch!
>
> Blog post: https://medium.com/@liberapay/the-second-year-of-liberapay-c017b73c9721
>
> #Liberapay #Anniversary #Retrospective #OpenSource #Donations #en

**Comment by Changaco** [comment]
https://www.facebook.com/Liberapay/posts/930505363774538

**Comment by Changaco** [comment]
French translation draft: https://medium.com/@liberapay/la-deuxi%C3%A8me-ann%C3%A9e-de-liberapay-12f10f0cbf39

**Comment by Changaco** [comment]
Submitted to https://linuxfr.org/.

**Comment by Changaco** [comment]
https://linuxfr.org/news/la-deuxieme-annee-de-liberapay

**Comment by Changaco** [comment]
https://mastodon.rocks/@Liberapay/99477607272087270
https://twitter.com/liberapay/status/960801870259326978

> « La deuxième année de Liberapay », bilan du développement de Liberapay à l'occasion du deuxième anniversaire de son lancement : https://linuxfr.org/news/la-deuxieme-annee-de-liberapay
>
> (Le magnifique dessin qui accompagne cette dépêche est de @davidrevoy, un grand merci à lui !)

**Comment by Changaco** [comment]
https://framasphere.org/posts/4561355

> ### Deux ans déjà !
>
> À l’occasion du deuxième anniversaire du lancement de Liberapay nous avons publié un bilan de son développement : https://linuxfr.org/news/la-deuxieme-annee-de-liberapay
>
> (Le magnifique dessin qui accompagne cette dépêche est de [David Revoy](https://framasphere.org/people/f36d0ea092e50134ec422a0000053625), un grand merci à lui !)
>
> #Liberapay #Anniversaire #Rétrospective #Libre #Dons #fr

**Comment by Changaco** [comment]
https://www.facebook.com/Liberapay/posts/932074596950948

**Comment by Changaco** [comment]
https://mastodon.rocks/@Liberapay/99558091611388409
https://twitter.com/liberapay/status/965952375331737601

> We're continuing to improve our support of multiple currencies, today we've added a currency selector to donation forms.

![screenshot of a donation form with the new currency selector](https://user-images.githubusercontent.com/1581590/36385648-5f771c48-1593-11e8-926d-2c0e9484762a.png)

**Comment by trebmuh** [comment]
In French on Mastodon : https://mastodon.rocks/@Liberapay/99558324750648066

**Comment by Changaco** [comment]
https://mastodon.rocks/@Liberapay/99631594400738724
https://twitter.com/liberapay/status/970656835647746048

> https://liberapay.com/ can now check your password and warn you if it appears in Troy Hunt's database of 500 million leaked passwords (see https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/ for details on this database).
>
> This is done automatically when you change your password, or when you log in with your password and it hasn't been checked in the last 6 months.
>
> ![screenshot of a warning notification shown after a user logged in with a weak common password](https://user-images.githubusercontent.com/1581590/36937121-ec74316a-1f0e-11e8-9d1e-811d58f7f86d.png)
