### ISSUE TITLE
News - March 2018

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#208]
This is Liberapay's news thread, its purpose is to help us achieve #29.

cc @liberapay/media-managers

**Comment by Changaco** [comment]
https://mastodon.rocks/@Liberapay/99631594400738724
https://twitter.com/liberapay/status/970656835647746048

> https://liberapay.com/ can now check your password and warn you if it appears in Troy Hunt's database of 500 million leaked passwords (see https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/ for details on this database).
>
> This is done automatically when you change your password, or when you log in with your password and it hasn't been checked in the last 6 months.
>
> ![screenshot of a warning notification shown after a user logged in with a weak common password](https://user-images.githubusercontent.com/1581590/36937121-ec74316a-1f0e-11e8-9d1e-811d58f7f86d.png)

**Comment by trebmuh** [comment]
On Mastodon in French : https://mastodon.rocks/@Liberapay/99631727469717232

**Comment by Changaco** [comment]
https://mastodon.xyz/@Liberapay/99705074120732120

> Good news: teams are no longer limited to a single currency.
>
> If you're a member of a team you can modify the currencies it accepts by editing its profile.
>
> In some cases you can also modify the currency of your "take" (by clicking on the currency symbol next to the amount input).
>
> Reminder: you can manage your team takes from https://liberapay.com/about/me/receiving/
>
> ![Screenshot of a currency settings form](https://user-images.githubusercontent.com/1581590/37566209-64fdf69a-2ab6-11e8-9a5b-aa1f3a5e8247.png)

https://twitter.com/liberapay/status/975359763675574273

**Comment by trebmuh** [comment]
On Mastodon in French : https://mastodon.xyz/@Liberapay/99711967289381125

**Comment by Changaco** [comment]
https://mastodon.xyz/@Liberapay/99733352649501309
https://twitter.com/liberapay/status/977169173330702337

> Yesterday the [@Krita@mastodon.art](https://mastodon.art/@Krita)|[@Krita_Painting](https://twitter.com/Krita_Painting) team released version 4.0 of their free and open source painting software. Did you know that you can support the development of this application on Liberapay? https://liberapay.com/Krita
>
> ![The new splash screen for Krita 4.0, created by Tyson Tan, shows Kiki among the plum blossoms.](https://krita.org/wp-content/uploads/2018/03/kiki_4.0_sm-1.png)

**Comment by trebmuh** [comment]
On Mastodon in French : https://mastodon.xyz/@Liberapay/99733603955131180

**Comment by trebmuh** [comment]
On Mastodon in French : https://mastodon.xyz/@Liberapay/99733624045761241

**Comment by Changaco** [comment]
@trebmuh « *free and open source* » c'est « gratuit et libre » (ou « libre et gratuit »), pas « libre et à source ouverte » (qui est redondant).

**Comment by trebmuh** [comment]
Attention, "source ouverte =! libre".

Ceci dit, j'ai [ajouté ce terme au document de traduction](https://github.com/liberapay/salon/wiki/Media-managers-guidelines#translation-terms) pour cohérence.

**Comment by jorgesumle** [comment]
> Ceci dit, j'ai ajouté ce terme au document de traduction pour cohérence.

Updated it with Spanish translations as well. Should we sort the glossary alphabetically and divide different languages?

> Yesterday the @Krita@mastodon.art|@Krita_Painting team released version 4.0 of their free and open source painting software. Did you know that you can support the development of this application on Liberapay? https://liberapay.com/Krita

**Spanish translation**

Ayer el equipo de @Krita publicó la versión 4.0 de su software libre y gratuito de dibujo. ¿Sabías que puedes apoyar el desarrollo de este programa en Liberapay? liberapay.com/Krita

**Comment by trebmuh** [comment]
> Updated it with Spanish translations as well.

Nice.

> Should we sort the glossary alphabetically 

Good idea. Done.

>and divide different languages?

I've reworked the page in a better way.

**Comment by Changaco** [comment]
https://mastodon.xyz/@Liberapay/99761637881743585
https://twitter.com/liberapay/status/978980751373930497

> Its now possible to see more than the top 18 accounts when exploring Liberapay: https://liberapay.com/explore
>
> Moreover we've added a new explorer for repositories: https://liberapay.com/explore/repositories
> 
> ![Screenshot of the new explorer of repositories. It shows that Mastodon's GitHub repository is the most starred software project on Liberapay.](https://6-28.mastodon.xyz/media_attachments/files/001/748/556/original/21ddc5b23233e660.png)

**Comment by trebmuh** [comment]
On Mastodon in French: https://mastodon.xyz/@Liberapay/99761857509394742

**Comment by trebmuh** [comment]
On Mastodon in French: https://mastodon.xyz/@Liberapay/99761864013107742

**Comment by trebmuh** [comment]
In French: https://mastodon.xyz/@Liberapay/99762220648026761

> Peertube, un projet pour une alternative décentralisée et collective aux hébergeurs de vidéos propriétaires et centralisés, a sorti sa version bêta il y a quelques jours. Voir https://joinpeertube.org/ .
> 
> Le développement Peertube est soutenu par Framasoft qui possède un compte sur liberapay : https://liberapay.com/Framasoft

**Comment by trebmuh** [comment]
Last post on the [diaspora* LP account](https://framasphere.org/people/ae296dc0b16f0133a1132a0000053625) is dating back 2 months ago. It'd be great to have a post in order to keep up the momentum on diaspora.

I'm planning to draft something on the coming days. Probably using the mastodon/tweeter/... posts from the last 2 months to start writing a summary of those 2 last months Liberapay activities.

**Comment by trebmuh** [comment]
Summary of the 2 last months on diaspora*:
- (FR) https://framasphere.org/posts/4798180
- (EN) https://framasphere.org/posts/4798196

> 
> ### Nouveautés autour de Liberapay
> 
> Voici un résumé des nouveautés des 2 derniers mois autour de #Liberapay.
> 
> Suite a un problème de mise à jour de l'instance sur laquelle nous avions notre ancien compte Liberapay, celui-ci est mort. Veuillez suivre [celui-ci](https://mastodon.xyz/@Liberapay) qui est notre nouveau compte principal, ainsi que notre [nouveau compte alternatif](https://mstdn.io/@Liberapay) (_note : [ancien compte Mastodon](https://mastodon.rocks/@Liberapay)_).
> 
> 
> Lors de [l'exploration sur le site de Liberapay](https://liberapay.com/explore), il est dorénavant possible de voir plus que les 18 premiers comptes. En outre, nous avons ajouté un [nouvel explorateur pour les dépôts](https://liberapay.com/explore/repositories).
> 
> 
> Les équipes ne sont plus limitées à une seule #devise. En effet, si vous êtes membre d'une équipe, vous pouvez modifier les #devises qu'elle accepte en éditant son profil. Dans certains cas, vous pouvez également modifier la devise de votre "part" (en cliquant sur le symbole de devise à côté de l'entrée du montant). Rappel : vous pouvez gérer vos parts dans l'équipe depuis [cette page sur Liberapay](https://liberapay.com/about/me/receiving)
> 
> 
> Côté toile, nous avons eu récemment un problème avec #Medium, le service hébergeant notre blog. Ils avaient suspendu notre compte et bloqué l'accès à tous nos billets publiés pour des raisons non-valables et avec un préavis de seulement 12 heures. Après une demande de notre part, le compte a été réactivé. Durant ce laps de temps, de nombreuses personnes ont offert leur aide en vue d'un hébergement de notre blog ailleurs. Nous pensions déjà à mettre en place notre propre truc pour de nombreuses raisons (ceci incluant le manque total de Medium pour le support des traductions). Bien entendu, nous vous en informerons avec un lien vers notre nouveau blog dès qu'il sera en fonction.
> 
> 
> Concernant [notre compte Mastodon](https://mastodon.xyz/@Liberapay), certains d'entre vous ont suggéré que nous devrions créer des comptes #Mastodon séparés pour les différentes langues avec lesquelles nous pouettons (actuellement : anglais, espagnol et français). Il se pourrait que nous finissions par faire ça, cependant nous pensons plutôt qu'il serait bien que le support multi-langues de Mastodon soit amélioré, et donc [nous avons soumis une proposition](https://github.com/tootsuite/mastodon/issues/6920).
> 
> 
> Nous pouvons maintenant vérifier votre mot de passe et vous alerter s'il apparaît dans [la base de données de Troy Hunt de 500 millions de mots-de-passe piratés](https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/). Ceci est fait automatiquement lorsque vous modifiez votre mot de passe, ou lorsque vous vous identifiez avec votre mot de passe et qu'il n'a pas été vérifié dans les 6 derniers mois.
> 
> 
> Nous avons continué d'améliorer notre support pour de multiples devises en ajoutant un sélecteur de devise aux formulaires de #dons.
> 
> 
> Des liens vers les pages Liberapay des développeurs d'applications sont maintenant présents dans F-Droid, et vous pouvez donc allez soutenir les projets que vous aimez.
> 
> Gaming on Linux dispose à présent d'un [compte Liberapay](https://liberapay.com/gamingonlinux/).
> 
> #Libre #fr #haveibeenpwned #FinancementParticipatif #Micropaiements #PrixLibre #Communs #french
> 
> ---------
> 
> ### News around Liberapay
> 
> Here is a summary of the 2 last months news about #Liberapay.
> 
> Our old #Mastodon account is dead, the entire database of the instance was lost during an update. Please follow [our new main account](https://mastodon.xyz/@Liberapay), as well as our [new fallback account](https://mstdn.io/@Liberapay) (_note: [old Mastodon account](https://mastodon.rocks/@Liberapay)_).
> 
> 
> When [exploring on the Liberapay website](https://liberapay.com/explore), it's now possible to see more than the top 18 accounts. Moreover we've added a [new explorer for repositories](https://liberapay.com/explore/repositories).
> 
> 
> Teams are no longer limited to a single currency. If you're a member of a team you can modify the #currencies it accepts by editing its profile. In some cases you can also modify the currency of your "take" (by clicking on the currency symbol next to the amount input). Reminder: you can manage your team takes from [this page on Liberapay](https://liberapay.com/about/me/receiving)
> 
> 
> Web side story, we recently had an issue with #Medium, our blog hosting service. They suspended our account and blocked access to all our published stories for invalid reasons and with only 12 hours notice. After we asked them, the account has been reinstated. During this time, a bunch of people offered to help with hosting our blog elsewhere. We were already planning to set up our own thing for various reasons (including Medium's complete lack of support for translations). Of course we'll toot a link to our new blog as soon as it's up.
> 
> 
> About [our Mastodon account](https://mastodon.xyz/@Liberapay), some of you have suggested that we should create separated Mastodon account for the different languages we are tooting with (currently: English, Spanish, and French). We could well ending doing so, however we're thinking that it'd be better that Mastodon multilingual support could be improved, and so [we have submitted a proposal](https://github.com/tootsuite/mastodon/issues/6920).
> 
> 
> We can now check your password and warn you if it appears in [Troy Hunt's database of 500M leaked passwords](https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/). This is done automatically when you change your password, or when you log in with your password and it hasn't been checked in the last 6 months.
> 
> We're continuing to improve our support of multiple currencies, we've added a currency selector to donation forms.
> 
> 
> Links to apps developers Liberapay's pages in F-Droid have been added, and you can then go to support the projects you like.
> 
> Gaming on Linux now got a [Liberapay account](https://liberapay.com/gamingonlinux/).
> 
> #OpenSource #Donations #en #haveibeenpwned #Crowdfunding #Micropayments #Commons

**Comment by Changaco** [comment]
https://mastodon.xyz/@Liberapay/99772329915103843
https://twitter.com/liberapay/status/979664915899273216

> Reminder: we also need your support, don't forget to donate if you can. https://liberapay.com/Liberapay/donate
>
> ![Screenshot of the profile page of the Liberapay team. Text: "Liberapay receives €260.03 per week from 541 patrons. Goal: €700.00"](https://user-images.githubusercontent.com/1581590/38134790-f6479edc-3414-11e8-95b3-15a2a4a34c2c.png)

**Comment by trebmuh** [comment]
In French : https://mastodon.xyz/@Liberapay/99772628086969537
> Rappel : nous avons également besoin de votre support, n'oubliez pas de donner si vous le pouvez.
> https://liberapay.com/Liberapay/donate

![lp](https://user-images.githubusercontent.com/8705846/38136470-ca99b202-341e-11e8-84a3-efb3f59effd5.png)

**Comment by Changaco** [comment]
@trebmuh Je pense que « soutien » conviendrait mieux que « support » dans cette phrase.

**Comment by trebmuh** [comment]
@Changaco : les deux fonctionnent.
