### ISSUE TITLE
Why is Malay translation reset to 0% on Weblate?

### ISSUE THREAD

**Issue by mnh48** [liberapay/salon#210]
I'm pretty sure I did some translations earlier but it suddenly shows as 0% translated on Weblate:
![image](https://user-images.githubusercontent.com/12217018/37212922-81bf122c-23eb-11e8-8487-c028e17a413d.png)

Are the translated strings moved to other place and I could continue translate it or it's a bug on Weblate that needs to be resolved first?

**Comment by Changaco** [comment]
It's a bug in Weblate: <https://github.com/WeblateOrg/weblate/issues/1895>.

**Comment by Changaco** [comment]
This has happened before, in the Esperanto translation I think, but it was only one string. This time it's the whole file.

**Comment by mnh48** [comment]
Oh, alright.
If that's the case, I will wait for the bug to be fixed first.

**Comment by Changaco** [comment]
The Malay translation is back to 69% on Weblate thanks to a forced "rescan".

**Comment by mnh48** [comment]
I'm closing this because it's fixed, thanks to the forced "rescan".

Even though the Malay translation is completed now, I'll always check both Weblate and GitHub from time to time for string update or whenever new sections need translations.
