### ISSUE TITLE
translations: working every day by small increments leads to spamming the commit logs

### ISSUE THREAD

**Issue by tuxayo** [liberapay/salon#211]
Such bite-sized daily work is the only way I've found to be motivated enough to translate hundreds of strings.

But this is generating noise in the commit logs and attributing me a ridiculous number of commits as if I was an active code contributor.
https://github.com/liberapay/liberapay.com/graphs/contributors?from=2017-07-24&to=2018-03-11&type=c

Is there something I can do to avoid that? (compatible with bite-sized daily work)

**Comment by Changaco** [comment]
It's not important, don't worry about it.

Besides, translators are active contributors. Of course it would be better if tools like GitHub were able to distinguish between different types of contributions (docs, translations, etc), but it's a minor shortcoming.

**Comment by tuxayo** [comment]
Thanks for removing that little weigh of my mind :)
Let's keep traducing!
