### ISSUE TITLE
News - April 2018

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#219]
This is Liberapay's news thread, its purpose is to help us achieve #29.

cc @liberapay/media-managers

**Comment by Changaco** [comment]
https://mastodon.xyz/@Liberapay/99813737114669528

> Status of Liberapay's polyglotism: the website is fully available in 14 languages! The new ones are Romanian and Malay.
>
> You can contribute on https://hosted.weblate.org/projects/liberapay/core/ and support the team financially through https://liberapay.com/Liberapay/donate
>
> (Image source: https://hosted.weblate.org/widgets/liberapay/-/multi-auto.svg)
>
> ![Screenshot of the linked graphic. It shows the list of languages that Liberapay is currently translated in, along with completion percentages and progress bars.](https://user-images.githubusercontent.com/1581590/38435835-32f4e916-39d3-11e8-8602-c5685929803f.png)

https://twitter.com/liberapay/status/982315285528174593

**Comment by trebmuh** [comment]
On mastodon in French : https://mastodon.xyz/@Liberapay/99813799204492776

> Statut de la prise en charge multi-langue de LiberaPay : le site est disponible complètement en 14 langues ! Les nouvelles sont le Roumain et le Malais.
> 
> Vous pouvez contribuer sur https://hosted.weblate.org/projects/liberapay/core/ et soutenir financièrement l'équipe avec https://liberapay.com/Liberapay/donate
> 
> (Image source : https://hosted.weblate.org/widgets/liberapay/-/multi-auto.svg)

**Comment by Changaco** [comment]
@trebmuh « État du multilinguisme de Liberapay » aurait été plus fidèle à l'original.

**Comment by Changaco** [comment]
https://twitter.com/liberapay/status/985175707352535047

> Good news: https://addons.mozilla.org/ now supports Liberapay as a donation platform that add-on developers can link to.
>
> ![](https://pbs.twimg.com/media/DawIox2W4AAFoVy.jpg)

**Comment by Changaco** [comment]
https://mastodon.xyz/@Liberapay/99970201314320254

> The well-known free software image editor GIMP now has its own team account on Liberapay: https://liberapay.com/GIMP
>
> This means that you can donate to the project as a whole, then its members will decide how to split the money, whereas previously you had to figure out by yourself who the contributors are and how much to donate to each one.
