### ISSUE TITLE
Add Liberapay to the Firefox Addon donation options

### ISSUE THREAD

**Issue by jorgesumle** [liberapay/salon#221]
People can't use a Liberapay URL as a donation URL.

![captura de pantalla de 2018-04-05 23-28-26](https://user-images.githubusercontent.com/14212780/38392842-339e7788-3929-11e8-8c0e-d1c25a7eabca.png)

**Comment by jorgesumle** [comment]
Asked via Mozilla IRC in #amo channel:

```
<jorgesumle> How can we add Liberapay as a donation option for Firefox Addons?
<jorgesumle> See https://github.com/liberapay/salon/issues/221
```

**Comment by revi** [comment]
Tracked at mozilla/addons#5423, PR at mozilla/addons-server#8007

**Comment by Changaco** [comment]
Thanks @revi and @jorgesumle!

**Comment by trebmuh** [comment]
Nice, well done!

**Comment by Changaco** [comment]
@jorgesumle Please confirm once you're able to add a Liberapay contribution URL to the liberapay-everywhere extension, so that we can toot/tweet about it.

**Comment by jorgesumle** [comment]
I can't yet. Maybe it isn't deployed. I'll try later today.

**Comment by jorgesumle** [comment]
> Please confirm once you're able to add a Liberapay contribution URL to the liberapay-everywhere extension, so that we can toot/tweet about it.

@Changaco https://github.com/liberapay/salon/issues/218#issuecomment-381326139
