### ISSUE TITLE
News - May 2018

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#227]
This is Liberapay's news thread, its purpose is to help us achieve #29.

cc @liberapay/media-managers

**Comment by Changaco** [comment]
https://mastodon.xyz/@Liberapay/99970201314320254

> The well-known free software image editor GIMP now has its own team account on Liberapay: https://liberapay.com/GIMP
>
> This means that you can donate to the project as a whole, then its members will decide how to split the money, whereas previously you had to figure out by yourself who the contributors are and how much to donate to each one.

**Comment by Changaco** [comment]
https://twitter.com/liberapay/status/992333894862213121

> You can now fund the development of the well-known free software image editor GIMP by donating to [@GIMP_Official](https://twitter.com/GIMP_Official) on Liberapay: https://liberapay.com/GIMP

**Comment by Changaco** [comment]
https://mastodon.xyz/@Liberapay/99987691970745696
https://twitter.com/liberapay/status/993446862316277760

> You can now attach a longer and nicer public name to your Liberapay account. https://liberapay.com/about/me/edit/username
>
> ![Screenshot of the "Name" tab of a user's profile settings](https://user-images.githubusercontent.com/1581590/39567214-86dd8ef2-4ebe-11e8-9b63-4a2c3a35291a.png)

**Comment by trebmuh** [comment]
https://mastodon.xyz/@Liberapay/99992980512487500

> Le logiciel libre d'édition d'image bien connu GIMP possède maintenant son propre compte d'équipe sur Liberapay : https://liberapay.com/GIMP
> 
> Cela signifie que vous pouvez donner au projet en tant que tel, puis ses membres décideront comment partager la monnaie, alors que précédemment, vous deviez vous débrouiller tout seul pour trouver qui étaient les contributeurs et combien donner à chacun d'entre eux.

**Comment by trebmuh** [comment]
https://mastodon.xyz/@Liberapay/99993013263830355

> Vous pouvez maintenant attacher un nom public plus long et plus sympa à votre compte Liberapay.
> https://liberapay.com/about/me/edit/username

![liberapay](https://user-images.githubusercontent.com/8705846/39750023-742a0dea-52b4-11e8-9a94-428421917ab1.png)

**Comment by Changaco** [comment]
[Vive la Liberapay! – Gratipay News](https://gratipay.news/vive-la-liberapay-14057a25eacb)

**Comment by trebmuh** [comment]
Last summary on the diaspora* LP account was dating back 2 months ago. Here is the new one:

- (FR) https://framasphere.org/posts/5089451
- (EN) https://framasphere.org/posts/5089459

> ### Nouveautés autour de Liberapay
> 
> Voici un résumé des nouveautés les plus importantes des mois d'Avril et de Mai à propos de #Liberapay.
> 
> Statut de la prise en charge multi-langue de LiberaPay : le site est disponible complètement en 14 langues ! Les nouvelles sont le Roumain et le Malais. Vous pouvez contribuer [sur hosted.weblate](https://hosted.weblate.org/projects/liberapay/core/) et soutenir financièrement l'équipe avec [son compte Liberapay](https://liberapay.com/Liberapay/donate).
> 
> [Addons.mozilla.org](https://addons.mozilla.org/) supporte à présent Liberapay en temps que plateforme de don à laquelle les développeurs d'add-on peuvent se lier.
> 
> Le logiciel libre d'édition d'image bien connu GIMP possède maintenant [son propre compte d'équipe sur Liberapay](https://liberapay.com/GIMP). Cela signifie que vous pouvez donner au projet en tant que tel, puis ses membres décideront comment partager la monnaie, alors que précédemment, vous deviez vous débrouiller tout seul pour trouver qui étaient les contributeurs et combien donner à chacun d'entre eux.
> 
> Vous pouvez maintenant attacher un nom public plus long et plus sympa à votre compte Liberapay. [Voir ici](https://liberapay.com/about/me/edit/username).
> 
> #Libre #fr #FinancementParticipatif #Micropaiements #PrixLibre #Communs #French

---

> ### News around Liberapay
> 
> 
> Here is a summary of the April and May months most important news about #Liberapay.
> 
> Status of Liberapay's polyglotism: the website is fully available in 14 languages! The new ones are Romanian and Malay. You can contribute [on hosted Weblate](https://hosted.weblate.org/projects/liberapay/core/) and support the team financially through [its Liberapay account](https://liberapay.com/Liberapay/donate).
> 
> [Addons.mozilla.org](https://addons.mozilla.org/) now supports Liberapay as a donation platform that add-on developers can link to.
> 
> The well-known free software image editor GIMP now has [its own team account on Liberapay](https://liberapay.com/GIMP). This means that you can donate to the project as a whole, then its members will decide how to split the money, whereas previously you had to figure out by yourself who the contributors are and how much to donate to each one.
> 
> You can now attach a longer and nicer public name to your Liberapay account. [See here](https://liberapay.com/about/me/edit/username).
> 
> #OpenSource #Donations #en #Crowdfunding #Micropayments #Commons
