### ISSUE TITLE
Liberapay is in danger of closing

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#232]
**[Update] Do not share this issue on social networks, we will do so ourselves if and when it becomes appropriate.**

---

Copy of <https://github.com/liberapay/liberapay.com/issues/374#issuecomment-393617792>:

> I have just received an email from mangopay saying that they want to terminate their contract with us because we have/had a few controversial users.
>
> I've replied, asking for confirmation, and information on how much time we have left.

As you probably know Liberapay cannot operate without a properly licensed payment partner, so if Mangopay really has decided to ban us then we're in trouble.

ping @liberapay/codirectors

**Comment by aggsol** [comment]
Awwwh FUCK! What can we do now? Alternatives?

**Comment by Changaco** [comment]
I'm currently looking into all the alternatives I can think of:

- contract with another licensed e-money emitter like [HiPay (Marketplace)](https://hipay.com/en/payment-solution-marketplace) or [Stripe (Connect)](https://stripe.com/connect)
- get our own e-money license and use a lower-level payment processor like [Braintree (Marketplace)](https://www.braintreepayments.com/products/braintree-marketplace)
- attempt to avoid the need for an e-money license by turning Liberapay into some kind of international cooperative

**Comment by Changaco** [comment]
Getting our own license is out, there's a minimum capital requirement of €350k.

**Comment by jorgesumle** [comment]
> attempt to avoid the need for an e-money license by turning Liberapay into some kind of international cooperative

That's doable, but it could take more time than the other alternatives and some legal knowledge.

> contract with another licensed e-money emitter like HiPay (Marketplace) or Stripe (Connect)

I guess that's the easiest thing for the short term. For the long term, we should be prepared for similar issues with vendors.

**Comment by mattbk** [comment]
Hate to suggest this, but are they not open to Liberapay booting the users to buy some time?

**Comment by Changaco** [comment]
@mattbk Whenever Mangopay is unhappy with a specific user they *order* us to close that account. This is what they did yesterday, and if I remember correctly it was the 3rd time since Liberapay's launch, but this time they're kicking out everyone else too.

**Comment by Changaco** [comment]
I haven't received any confirmation from mangopay today, which means that we probably won't get it before Monday at best.

**Comment by Changaco** [comment]
The user they ordered us to ban yesterday joined Liberapay two years ago and has received less than €400 since then. It's unclear how Mangopay "found out" about this controversial user, they may have been contacted by a third party.

**Comment by trebmuh** [comment]
Practical question here: what does that means/involves for the current users with money in their wallet **if** Mangopay is going to terminate the contract with LP?

**Comment by Changaco** [comment]
Mangopay would have to repay all users by doing refunds or payouts.

**Comment by Changaco** [comment]
Actually if I'm interpreting the contract correctly they have to contact all users to ask for consent to close the wallets and instructions on where to transfer the funds.

**Comment by Changaco** [comment]
Other alternative:

- avoid EU regulations by operating from the US like Gratipay did

**Comment by aggsol** [comment]
The sole reason I joined Liberapay was because it is EU based and operating in the EU. Especially that SEPA transactions just work. This is horrible.

**Comment by Changaco** [comment]
This issue is now being shared on social networks. Doing that is inappropriate at this early stage.

**Comment by albjeremias** [comment]
I'm not sure.. but might be relevant: https://fair-coin.org/en/use-cases

**Comment by tuxayo** [comment]
@Changaco 
> Doing that is inappropriate at this early stage and only sends me a signal that discussing sensitive matters publicly is not a good idea.

I'm not sure. Such transparency and open discussion also build trust. There might be a balance though.

Thanks for your work in handling all this mess.

**Comment by jelv** [comment]
I hope you can work it out with Mangopay. 
How would the cooperative work for Liberapay?

**Comment by Changaco** [comment]
The basic idea of the "cooperative" alternative is that everyone who receives money on the platform would be a member of the Liberapay legal entity, and that all the collected funds would legally belong to that entity instead of to each individual user. This should remove the need for an e-money license since we would no longer be holding money that belongs to someone else.

This model would require rewriting the bylaws, the rules of procedure and the terms of service of Liberapay. We would have to completely abandon the neutrality principle and approve all members manually like Gratipay did.

**Comment by jelv** [comment]
Is [Adyen MarketPay](https://www.adyen.com/our-solution/online-payments/marketplaces) also a option?

**Comment by Changaco** [comment]
@jelv Probably not, but I've added it to the list in <https://github.com/liberapay/liberapay.com/issues/374>.

**Comment by MartinDelille** [comment]
Do we really need to close the website if Mangopay block us? We could just pause the service, inform everyone no? 

This would have a massive effect on the social network and would be a very bad buzz for Mangopay. Its marketing service will face a communication crisis and we may have argument to reactivate Liberapay then (with a short cutage in the service).

Can we handle such cutage technically?

**Comment by jelv** [comment]
For the people on the platform continuity would be best option.

If we could change to another supplier it would be good to know how they handle our neutral position. Has there been in contact with other e-money emmiters on this topic?

**Comment by Changaco** [comment]
@MartinDelille Having a "bad relationship" with our payment partner is not a good idea. If Mangopay doesn't want to work with us, then we don't want to work with them.

@jelv I haven't initiated any contact with potential new partners yet.

**Comment by Changaco** [comment]
Regarding the neutrality issue, I did notice this:

![Screenshot of solarisBank's homepage](https://user-images.githubusercontent.com/1581590/41090966-c2d94f5c-6a45-11e8-82ca-c8776cef33fa.png)

(Screenshot of <https://www.solarisbank.com/en/>.)

However just because we use the same word doesn't necessarily mean that we're talking about the same thing.

**Comment by Changaco** [comment]
It's been two weeks, I haven't received any email or letter from Mangopay.

**Comment by mattbk** [comment]
> It's been two weeks, I haven't received any email or letter from Mangopay.

That makes me worry that they're going to cut Liberapay off without warning. What's the level of effort required to switch to a new payment processor?

**Comment by Changaco** [comment]
> That makes me worry that they're going to cut Liberapay off without warning.

It's more likely that they haven't reached a final decision yet.

The normal procedure for termination of the contract is to not renew it, and that means we would have until 2019-02-03 to migrate, because the contract is renewed yearly based on the date of the first transaction. Moreover Mangopay has to formally notify us of their intention not to renew the contract at least 3 months before the renewal date.

The contract does have a clause for early termination that Mangopay could use, by claiming that we have failed to fulfil our obligations, but that would be shady and very stupid.

> What's the level of effort required to switch to a new payment processor?

Very high, higher than it was for Gratipay.

**Comment by mattbk** [comment]
Thanks, that was very helpful.

**Comment by trebmuh** [comment]
@Changaco still no news from Mangopay?

**Comment by Changaco** [comment]
Looks like your concern was justified @mattbk, they did cut off our access without warning, albeit for "technical" reasons.

**Comment by mattbk** [comment]
Sometimes I hate being right. Wish there was something I could contribute from here.

**Comment by tuxayo** [comment]
There this nothing really appropriate in the [reactions one can put on a comment on GitHub](https://developer.github.com/v3/reactions/#reaction-types). So here is a substitute: 
![fuuu](https://user-images.githubusercontent.com/2678215/41988214-bbb8ca44-7a3b-11e8-9bd1-bd004299a556.png)

**Comment by eldelacajita** [comment]
WTF 😮 😓  

I hope @Changaco can figure it out with them in the short term. And then... let's think how we can work with him in getting rid of this "dependency" for good. _If_ there is a way to do it, that is.

**Comment by jelv** [comment]
Damn, that is the bad scenario. Best of luck and let us know if we can help you in any way.

**Comment by tuxayo** [comment]
Is it useful to ask them in public to confirm that they indeed blocked Liberapay? https://twitter.com/tuxayo/status/1012020996025528325

**Comment by aggsol** [comment]
@tuxayo No, they will not talk in public about business with a specific customer.

**Comment by Changaco** [comment]
I have just received the termination letter from Mangopay, after having been silent for a month they have chosen to end the contract in 30 days!

(Edit: the letter is dated June 26th.)

**Comment by Changaco** [comment]
I'm wondering if we should run a modified payday to flush all funds from donors to recipients.

**Comment by trebmuh** [comment]
Does that mean that the users will have to withdraw their money within those 30 days?

What is the plan from your side @Changaco ? Switching to another payment processor? Interruption of service? Other?

**Comment by tuxayo** [comment]
@Changaco 
> I'm wondering if we should run a modified payday to flush all funds from donors to recipients.

I'm not sure that will be well perceived.

**Comment by Changaco** [comment]
@trebmuh I'm trying to figure it out…

I doubt that we can switch to another payment service provider within 30 days.

**Comment by trebmuh** [comment]
Yep', that is my fear behind this "_30 days notice_". I'm sending you my best energy @Changaco since I can't help much here. Let me know if there is something I can do.

**Comment by Changaco** [comment]
Extra note on the deadline: the letter says "30 days from the date on which the registered mail was *sent*", that means July 26th, exactly 4 weeks from today.

**Comment by Changaco** [comment]
Some stats: we currently have €97,176.75 and $18,310.73 in 2356 user accounts. That's a lot of money and people to deal with in only 4 weeks…

**Comment by mnh48** [comment]
I don't really know how to help in this case because I don't live in EU...

----
offtopic:
welp, at least the letter arrived faster...

I have had official letters that only arrived 7 days after it's sent (several times, not once) and it includes bank statements and some bills... because of the postmen are lazy somehow...

that kind of delay that would be disastrous if it happened to you as it means even shorter time to respond or even to do anything...

**Comment by trebmuh** [comment]
@Changaco : True. We need to keep communicating properly during this time.

I'm available until Sunday the 8th of July to help with this. Then, I'll not be able to keep up with it until the beginning of August (being on a street theater show tour). Unfortunate timing.

As usual, let me know what I can do to help you (here or on IRC).

**Comment by enricduran** [comment]
Hi  @Changaco 

Im founder of https://bankofthecommons.coop and Faircoop.  We could study to integrate your service in our cooperative framework. We also have collaboration with fairbill.com who have a payment processor visa license.
If interested, tell me, which way we can talk about it

**Comment by Zatalyz** [comment]
Thanks Enricduran for your proposal. We're gonna watch this.

We need time, that's the priority. We obviously need to change payment operators, but this cannot be done in 4 weeks. In article 10 of the Terms of Service, Mangopay states that a termination takes 2 months, so already making them respect this would be better. 

I propose to contact the Quadrature du net, they have lawyers who may find a way to talk to Mangopay to save time. I need the letter scan for that. Changaco, maybe you can hide the names on the letter and put it here, where everyone can see it?

We must also communicate with our users. Let's write together on a pad : [https://mypads.framapad.org/p/liberapay-jtbc77z1](https://mypads.framapad.org/p/liberapay-jtbc77z1) . 
The goal is to write a post to put on the blog (and share it again), where to explain what is happening to people and what they can do. We must be transparent and avoid any misinterpretation in public communication. Redirecting towards a long and well constructed argument will be better than messages too short on mastodon/twitter, which may lead us to problematic simplifications. 

I'm contacting some friendly librist organizations for more help.

**Comment by Changaco** [comment]
I'm not sure that publicly posting a copy of the letter would be appropriate, even if partially obfuscated.

I will send a copy to @Zatalyz and the other codirectors in private for now.

**Comment by albjeremias** [comment]
here an intro to what faircoin is :) http://wiki.p2pfoundation.net/Faircoin

 ... "we want to promote Faircoin as an option for ethical savings, facilitated by multiple services making it a useful tool for initiatives working toward the economic empowerment of active subjects of social change." ...

**Comment by tuxayo** [comment]
@albjeremias IMO that's a too huge step to not support at all fiat money (EUR, USD, etc) and support only cryptocurrencies. It's probable that Liberapay won't be sustainable like that. (to continue to fund it's development and to still be an option for the current projects using it).

**Comment by eldelacajita** [comment]
So there are 3 parallel lines of work now: 

1. Trying to gain some time with Mangopay, as @Zatalyz suggests.
2. Trying to get another payment processor before Mangopay cuts off, with two possible outcomes:
- Success! And everything will be back to start. Still risky on the long term, so should continue to (4).
- Failure. Then I'd suggest trying to frame this as a "graceful shutdown" or a "pit stop" and turn to (4).
3. Handle communication properly during all this, preparing users for both scenarios.

And then...

4. Look for a _very_ reliable payment processor or a long-term alternative model (coop, etc.)

I agree that communicating with the users is key. Some thoughts on this: 
- Make them aware, try to avoid a surprising closing.
- Explain the possible outcomes of the situation, and plans about them.
- Give them voice. Maybe a poll on (e. g.) how to handle their funds? An open discussion thread?
- Keep them somehow connected to Liberapay through the situation, even if it stops working for some time. Is it possible to send newsletters or "special" notification emails to all users?

I'll outline what I think could be the _key communication messages_ [on the pad started](https://mypads.framapad.org/p/liberapay-jtbc77z1) by @Zatalyz.

**Comment by Zatalyz** [comment]
I send mail to [Quadrature du net](https://www.laquadrature.net) and [Framasoft](https://framasoft.org/), I hope that some people from these organizations can help us.

**Comment by Changaco** [comment]
@eldelacajita That's a good summary, thanks.

**Comment by Changaco** [comment]
I've drafted a response to Mangopay's letter and I'll be discussing the situation with the other codirectors by phone in 30 minutes.

**Comment by Changaco** [comment]
I've opened a Stripe account for Liberapay and am investigating the possibility, if no better solution can be found, of at least keeping Liberapay alive as a simple facilitator of Stripe payments, somewhat like a platform version of the self-hosted [fosspay](https://github.com/SirCmpwn/fosspay) webapp.

**Comment by Changaco** [comment]
I'm working on building tools that will allow users to close their MangoPay accounts easily in a clean way.

I would like donors to have the option to send all the funds that would have been distributed over time in a single burst, and for this to be properly recorded and visible to the recipients. For example a donor who is sending €1 per week and has €40 in his wallet would be able to send all of it in a single transfer that the recipient would see as "€40 corresponding to 40 weeks of a €1 donation".

**Comment by Siesh1oo** [comment]
@Changaco: In case the worst case is unavoidable and liberapay has to stop paying out ongoing donations, it would be essential for projects to have a tool to send a message to all anonymous donors, to notify them about the situation, and how they can continue to support their projects via other channels.

Let’s hope this is avoidable, and liberapay can continue to operate in some way without disrupting established relationships between donors and projects too much! Thank you for all your effort!

**Comment by Siesh1oo** [comment]
@Changaco: another thought. from the legal standpoint, as registered non-Profit organization in EU, liberapay should be able to operate (for European donors and projects) by means of SEPA direct debit and SEPA credit transfer, fees should be even lower than through a dedicated payment provider? The GNUCash libraries contain command line tools to automate SEPA transactions through the common banking interfaces (commonly used by German non-Profit organisations to collect member fees and pay bills).

Paperwork and integration effort is reasonable.

This way liberapay would at least be able to operate efficiently for European donors and projects, non-European could be processed through stripe until a better solution is found?

**Comment by Siesh1oo** [comment]
For reference, an example from FreiFunk eV describing commands and procedures for direct debit and credit transfer submission, also templates for the required notification documents (email) for donors/members: https://wiki.ffnw.de/Verein/Schatzmeister (German only, sorry, maybe automatic translation or a friendly friend can help)

**Comment by Changaco** [comment]
@Siesh1oo No, we can't hold our users' money in our own bank account.

**Comment by enricduran** [comment]
@Changaco   @Siesh1oo   One thing we can do if that is the need is to open bank account for liberapay -becoming liberapay member of our coop - and hold users money there, for letting you order transfers.  We have an api that you could use for automatizing it. too

**Comment by mattbk** [comment]
Users wouldn't need to be coop members though, correct?

**Comment by Changaco** [comment]
@enricduran You do not appear to be in any position to help us.

In case my previous comment wasn't clear enough: it would be illegal to hold our users' money in a single bank account that is controlled by us, because we do not have an e-money emitter license.

**Comment by enricduran** [comment]
@Changaco  well, we are experienced in sort out legal requirements.   We have a coop where legal membership is 1 euro.  Then it would be fully legal for us to hold this money in behalf of liberapay certifiying that this 1 euro has been received for all members.

**Comment by Siesh1oo** [comment]
@Changaco wrote: 
> @Siesh1oo No, we can't hold our users' money in our own bank account.

I am not sure if I understand, but feel this is important. My interpretation until now was that users (=donors) donate to the registered liberapay association, which in turn gives out sponsorship to receivers (legally I understood this as stipend, which would be perfectly legal here, if the giving non-profit association is allowed by its given bylaws to use this money for stipends, benefactions, non-profit and charitable causes – my assumption was that due to harmonized EU legislation similar regulations apply in France).

In this case the donated money would obviously be held in liberabpay's own name and account – and that's how non-profit foundations usually work world-wide, ... but your concerns kind if suggest that the statutes define liberapay's purpose more in terms of a payment processor (or trying to avoid being one), and not charitable foundation?

Is Liberapay registered as "Association Loi 1901"? (and if not, could such realistically happen within the given notice period?)

**Comment by Changaco** [comment]
@Siesh1oo Your interpretation was incorrect, donations through Liberapay do not go to the Liberapay association (except the donations to the association's account: <https://liberapay.com/LiberapayOrg/>). The money in a Liberapay account belongs to the account owner, not to Liberapay.

> Is Liberapay registered as "Association Loi 1901"?

Yes.

**Comment by Siesh1oo** [comment]
@Changaco:
Would a re-dedication to the liberapay association as trustee be workable? Such a campaign would probably have a less-than-100% conversion rate, but maintain established trust and networks...

**Comment by eldelacajita** [comment]
> The money in a Liberapay account belongs to the account owner, not to Liberapay.
So basically, when a user registers in Liberapay, an account for them with MangoPay is created. 

So Liberapay is acting as an interface between the MangoPay accounts of different users, and does things like arranging paydays in a more efficent way to minimize the number of transactions. Would it be any different by using Stripe? Would there be any noticeable user-facing change?

BTW, I think @enricduran's experience with money, cooperatives and legal stuff could help Liberapay find an alternative model for the long term. It may be worth a direct call with him.

**Comment by Changaco** [comment]
@Siesh1oo No. Before asking users to transfer property to Liberapay we would want to turn it into a cooperative, as outlined in <https://github.com/liberapay/salon/issues/232#issuecomment-394616139>.

@eldelacajita Stripe Connect is quite different from MangoPay, the changes would be very noticeable.

With MangoPay donors have accounts and there's no limit to how long their money can stay in them. Stripe Connect doesn't provide accounts for donors, and it only allows holding funds for 90 days at most.

With Stripe Connect funding all of a user's donations with a single payment would be very difficult, which is a problem because a micro-donation platform that doesn't provide "aggregation" is much less interesting than one that does. Moreover it seems that Stripe exposes the address and phone number of a payment recipient to the payer, because it's designed for businesses, but this would probably be unacceptable for many of our users.

**Comment by trebmuh** [comment]
> ... exposes the address and phone number of a payment recipient to the payer, because it's designed for businesses, but this would probably be unacceptable for many of our users.

I agree, I choose LiberaPay because of the fact that I don't know who is donating to me/my_project an that's the way I like. This is the **pure-donation** vision.

(_by the way, I'm not opposed to have a feature leaving the donor being showed to the receiver **if both the donor and the receiver** choose that_)

**Comment by eldelacajita** [comment]
Thanks for the clarification, @Changaco. That's a big change, indeed.

**Comment by Zatalyz** [comment]
News about our actions:
- we managed to contact some lawyers in Mangopay. We did not understand all their motivations, but the discussion is engaged and it is positive. We make them a proposal to avoid closure. We also send them a letter to refuse the current terms of termination.
- The [communication](https://mypads.framapad.org/mypads/?/mypads/group/public-doua37o9/pad/view/liberapay-jtbc77z1) is written in English and French. You can proofread and correct until Friday 6 July, 16H UTC. We hope to have a response from Mangopay to our proposal by then. After that, we will officially publish it. 
- co-directors work about the possible action plans, probably changes for Liberapay (better than close...).

Thank you all for your support, we have had a lot of help in recent days. Thanks to the mobilization of everyone. We hope it will work!

**Comment by eldelacajita** [comment]
Thank so much for the update, @Zatalyz!

Is it OK if I make proposed changes to the English text beyond small errors and stuff? Like rephrasing and reordering sentences... I created a saved revision so you can easily go back to the original.

**Comment by Zatalyz** [comment]
Ho yes, my english is so bad ! You can rewrite, thanks :) I hope you can understand what I write... or help you to write about this situation.

**Comment by eldelacajita** [comment]
Haha, don't worry, it was perfectly clear. I mostly made small adjustments you can now review. The only major changes were: 
- Moving a couple of paragraphs up in the text, which made more sense. See notes in the text.
- Adding some content to the last paragraph, to give it a more positive/proactive approach and suggest a way forward for the platform and its community. That one should be definitely be reviewed. This is it:

> We want to make clear that whether we have to close accounts on July 26th or we manage to find a quick solution to keep the site working, we will continue to fight for a solidarity-based alternative for financing the commons, anchored in the European space. We will do our best to ensure the continuity of the service beyond that date. Even if we come to a temporary halt in our services, we sincerely hope that you, our beloved community, consider sticking around and support our efforts until we can bring Liberapay to a rebirth as an even better and more resilient platform. This is not the end.

I still feel the text is a bit long in details about the situation and short on explaining the possible outcomes and the options for the community.

And I also think there should be some community-related actions beyond this communication. It is probably going to stir up debate, so we could prepare a place for that debate to properly and healthily take place. This would let the community express itself, and would give us all more insight on what possible outcomes and situations could come out of this. We might find great proposals or even effective solutions. 

In addition, I would propose a small poll and a specific topic for debate: "If the moment comes to choose, would you withdraw your money, or instantly donate it to the creators you support? Check the debate about the possible implications of that choice *here*". This would make that decission collective and reasoned, instead of individual and probably driven by fear or uncertainty.

I would also suggest preparing a new discussion thread about the situation in general, different from this one, and linked from the text.

**Comment by Zatalyz** [comment]
Good redesign, it's clearer and better built. Thank you. I have noted the deletion of a paragraph, as suggested.

> so we could prepare a place for that debate to properly and healthily take place. 

I am agree but... where ?  

> I would also suggest preparing a new discussion thread about the situation in general, different from this one, and linked from the text.

Be free to act :)

**Comment by eldelacajita** [comment]
> I am agree but... where ?

That's a good question. Right now the only platforms we are using are Medium and Github, right? None of them are ideal for open debate, but we can manage. We can create two new Github issues and link them to the text: 
- A general debate thread
- A separate thread (or not?) for discussing the "what to do with our money" thing.

In any case, if the text is published on Medium, many people would just comment there, so we should count on that. **Important:** Is there a way to publish this text also on Liberapay itself, and mail it to all registered users?

> Be free to act :)

Ok, I can create those topics, begin them with a short introduction, etc. Just would like to have the opinion of @Changaco and the rest of you in this particular line of action.

**Comment by jelv** [comment]
There is not really a good place for debate. Gitter and Github is to technical. Social media to open to just hear from the users. For a good debate you need a forum or user only place for that. But the question is more do we need more input on a topic? Or more help? We can ask for that directly and to contact via email or social media.

A poll on what to do is not a high priority in my opinion. It's the people's money so let them choose. And if they do not choose give it back. We can use the current close account code for that.

**Comment by sub26nico** [comment]
Riot (https://about.riot.im/) is a solution to debate.

**Comment by mattbk** [comment]
Loomio?

**Comment by eldelacajita** [comment]
> But the question is more do we need more input on a topic? 

I'd say it's not about getting more inputs, but about letting people ask questions, debate with each other, see other opinions, get updated as the process goes on... and have a collective catharsis about it. I've seen many sites close without even listening to their users, and it's a bit disheartening. And, who knows, we _may_ get good ideas out of it. 

_Edit: Actually, the best scenario in case of having to temporarily close Liberapay is having users stick around, remain aware and wait until it's back. That won't happen if there isn't at least some community feeling and some collective reflection about this, I think._

About the tool to use... do you think it's worth opening new channels for this? I'm not sure. We will barely find the perfect one, and people would have to create new accounts anyway. I think a direct link to a thread on Github may just do the job as well. It's not difficult to use or technical _per se_, it's just a simple thread of replies.

**Comment by bnjbvr** [comment]
To wit: if you want a broader discourse with the most people, please make sure you're using a platform that *doesn't* require signups, like ye olde IRC channels (accessible even on the web, thanks to web clients), or rocket.chat (i think?).

**Comment by trebmuh** [comment]
We already have an IRC channel : #liberapay on freenode.

**Comment by tuxayo** [comment]
>  platform that doesn't require signups, like ye olde IRC channels (accessible even on the web, thanks to web clients), or rocket.chat (i think?).

Just for the info: Riot also doesn't require an account and is accessible on the web. And it has history which can help people not coming right on time.
But not sure if the UX is straightforward enough when using it for the first time.

**Comment by eldelacajita** [comment]
Considering all this, I'd suggest using two/three existing channels, linked from the text: 
- Github issue: For a simple, clear debate thread that can be reviewed afterwards. With login.
- IRC channel (or Riot?): For instant questions, chit chat, etc. with no login required. A chat is generally more difficult to follow and read afterwards, even if it keeps a log, but is still useful.
- (Medium comments: if we publish the text on Medium, that is. Also requires an account.)

What do you think? Enough choice with those three?

Regardless of the channels we choose, at least one of us could be watching each channel from time to time, replying to questions or providing the relevant info.

PS: I tried using Riot without registering a user, and it feels kinda cumbersome and slow. Is it only me?

**Comment by trebmuh** [comment]
Using the IRC channel is as easy as [clicking on this link](http://webchat.freenode.net/?channels=liberapay), choosing a name, filling up the captcha, clicking on "connect", done.

**Comment by tuxayo** [comment]
@eldelacajita 
> PS: I tried using Riot without registering a user, and it feels kinda cumbersome and slow. Is it only me?

No, thanks for confirming my impression.

**Comment by heinezen** [comment]
> IRC channel (or Riot?): ...

@eldelacajita Why not both? Matrix/Riot rooms can be bridged to IRC channel, so that messages from the IRC chat appear in the Riot room and vice versa. It should also be pretty easy to set up in the Riot UI.

**Comment by tuxayo** [comment]
@heinezen 
> @eldelacajita Why not both? Matrix/Riot rooms can be bridged to IRC channel

Then there is nothing to do. People who want to use Riot will be able to join the channel. As there is a brigde for Freenode.

link here: https://riot.im/app/#/room/#freenode_#liberapay:matrix.org

But from my experience, there is **more** than a 10 seconds latency when sending and receiving a message. And with the bridge on Freenode, one can't be PMed by non-registered user. (something about the defaut IRC mode of the bridge which forbids that and I could find how to change it)

**Comment by eldelacajita** [comment]
So, let's say IRC is the main channel, and the rest are bridged to it. There are still several decisions that have to be taken ASAP for the communication actions to work coherently: 

- When and where is the text going to be published? Who will publish it?
- Is there a way to publish the text also on Liberapay itself, and mail it to all registered users?
- Who will share it on social media?
- Who will take care (read messages, answer to questions, clarify things) of each channel?
- Can @Changaco, @Zatalyz or someone else keep us informed here so we can communicate the same things?

I could take care of creating and moderating a new Github thread, ideally in collaboration with someone else. As I am travelling right now, I wouldn't be able to regularly check the chat channels.

**Comment by Changaco** [comment]
We've just received confirmation from MangoPay that they won't reverse their decision to cut us off, despite our proposal to "fix" Liberapay so that it would no longer be a problem for them.

**Comment by jelv** [comment]
Did you get the extra month before closing?

**Comment by Changaco** [comment]
MangoPay's message didn't include a termination date. I immediately replied asking for clarification on that.

**Comment by Changaco** [comment]
I'm planning to publish a blog post soon, probably tomorrow. It will contain a link to the "Emptying your wallet" page from <https://github.com/liberapay/liberapay.com/pull/1169>.

After that I'll see about emailing all active users.

**Comment by ZiiX** [comment]
If y’all need €350K then you should just ask for it. We will try to get your back. 💪 Get on the Fediverse & lets do this.

**Comment by Changaco** [comment]
Blog post draft: https://medium.com/@liberapay/liberapay-is-in-trouble-b58b40714d82

**Comment by mattbk** [comment]
There's a note in the donor section, but should also be a note in the team section that all teams should increase their takes so they can actually accept money.

"normal procedure " should have a link if possible so people can see the source for this information.

Inconsistent capitalization of "Mangopay." From their website, I can't even tell what the right way is (IMHO "MANGOPAY" is an annoying style that they use).

Should link to whatever ticket/PR includes the new distribution system. (I'm not super excited about it as a donor because it changes how often I can change donation amounts, but that's for another place.)

**Comment by agateblue** [comment]
Thanks for sharing the draft @Changaco. 

The part about switching from recurring donations, maybe I missed something but I think the phrasing is a bit weird:

> So, we’re changing our approach of recurrent donations. Instead of distributing them weekly we’re going to distribute them as soon as the money arrives. For example instead of disbursing a payment of €26 for a weekly donation of €0.50 as 52 weekly transfers of €0.50, we’ll do a single transfer of €26 and inform the recipient that it corresponds to “52 weeks of €0.50”.

Basically, there won't be any recurring donations anymore, so it is a bit weird to refer to « weeks » and « weekly » periods. AFAIU, it would be a basic donation system (you give X€, the creator receives X€, period).

**Comment by jelv** [comment]
In the begin also mention that you end with what it will mean for the future of Liberapay. 

Also start the few paragraphs with a quick summery of whats coming and then explain it further. That makes it easier to read

**Comment by Changaco** [comment]
> There's a note in the donor section, but should also be a note in the team section that all teams should increase their takes so they can actually accept money.

Added.

> "normal procedure " should have a link if possible so people can see the source for this information.

It's in the Mangopay contract, we can't really link to it.

> Inconsistent capitalization of "Mangopay." From their website, I can't even tell what the right way is (IMHO "MANGOPAY" is an annoying style that they use).

AFAIK the official style is all-caps. I also think it's annoying so I'm using "Mangopay" instead.

> Should link to whatever ticket/PR includes the new distribution system. (I'm not super excited about it as a donor because it changes how often I can change donation amounts, but that's for another place.)

Created <https://github.com/liberapay/liberapay.com/issues/1171>.

**Comment by Changaco** [comment]
> Basically, there won't be any recurring donations anymore, so it is a bit weird to refer to « weeks » and « weekly » periods. AFAIU, it would be a basic donation system (you give X€, the creator receives X€, period).

The difference with a basic donation system is that all involved parties (the donor, us, and the recipient) know that the X€ received correspond to N weeks of income, and that if all goes well the donor will pay X€ again in N weeks.

**Comment by Changaco** [comment]
> In the begin also mention that you end with what it will mean for the future of Liberapay.

Done.

> Also start the few paragraphs with a quick summery of whats coming and then explain it further. That makes it easier to read

I'm not sure what you mean here, but I'm out of time anyway so…

**Comment by Changaco** [comment]
The blog post is published: <https://medium.com/liberapay-blog/liberapay-is-in-trouble-b58b40714d82>.

**Comment by tuxayo** [comment]
Damn I got distracted and lost few hours before finishing writing this ^^"


> Blog post draft: https://medium.com/@liberapay/liberapay-is-in-trouble-b58b40714d82

> We’ve tried to understand their concerns, they seemed related to the fact that Liberapay is open to everyone, so we proposed to review every user and block any potentially problematic account

From what I understood there was some kind of strong neutrality towards who could use Liberapay to collect donations, which is really great. But I couldn't refind that. If that was the case, will the Mangopay issues change Liberapay's "policy" in this regard?

**Comment by LiamDawe** [comment]
Will you turn off the quarantine then, so us creators can get our funds right away? Don't like the idea of losing some of it if they do abruptly cut you off.

**Comment by markasoftware** [comment]
In light of this, could https://github.com/liberapay/liberapay.com/issues/364 be an option? Or would that also require some sort of e-money license?

**Comment by dixonge** [comment]
I see that MangoPay has finally responded, sort of...

https://www.mangopay.com/blog/liberapay/

**Comment by mattbk** [comment]
> https://www.mangopay.com/blog/liberapay/ 

is gone. Did anyone save a copy?

**Comment by jelv** [comment]
> > https://www.mangopay.com/blog/liberapay/
> 
> is gone. Did anyone save a copy?

Is this the full message? https://archive.fo/N6RCp

**Comment by mattbk** [comment]
Nice work. I only checked the Wayback Machine.

**Comment by stevenroose** [comment]
Just for curiosity's sake, what happened to this? Did Liberapay just migrate to another payment processor?

**Comment by trebmuh** [comment]
Yes, Liberapay moved to Paypal and Stripe as payment processors.

**Comment by Changaco** [comment]
Liberapay didn't “just” migrate to another payment processor, it was significantly modified to work with different payment processors.

If you want to know more, I suggest you read the blog posts: https://medium.com/liberapay-blog

**Comment by stevenroose** [comment]
> Liberapay didn't “just” migrate to another payment processor, it was significantly modified to work with different payment processors.
> 
> If you want to know more, I suggest you read the blog posts: https://medium.com/liberapay-blog

Sorry, didn't want to sound as if changing was not a big deal. I just wondered if perhaps the original payment processor changed their minds when Liberapay went public with their threats.

If course I'm happy to see that Liberapay overcame this trouble!
