### ISSUE TITLE
Tor users are being blocked

### ISSUE THREAD

**Issue by jorgesumle** [liberapay/salon#233]
![screenshot at 2018-06-02 18 22 49](https://user-images.githubusercontent.com/14212780/40878477-69ff8422-6681-11e8-9dcf-4748c1ec5496.png)

**Comment by mnh48** [comment]
Are you sure that JavaScript is indeed enabled?
Even on normal browser, you'll be blocked if you disabled JavaScript, so please enable JavaScript on Tor Browser and try again.

**Comment by jorgesumle** [comment]
> Are you sure that JavaScript is indeed enabled?

Yes, I usually browse the Internet with JavaScript disabled.

> Even on normal browser, you'll be blocked if you disabled JavaScript

Censorship against privacy-aware people is pretty bad. Previously, you could browse Liberapay with JavaScript disabled.

**Comment by Changaco** [comment]
We are currently in "Under Attack" mode to protect the server from intensive scans.

> Censorship against privacy-aware people is pretty bad.

A JavaScript challenge is not censorship, and it doesn't specifically target "privacy-aware people".

**Comment by jorgesumle** [comment]
> We are currently in "Under Attack" mode to protect the server from intensive scans.

There are other ways to prevent intensive scans, it should be changed to a friendlier one.

> A JavaScript challenge is not censorship, and it doesn't specifically target "privacy-aware people".

So far as it prevents people from accessing the site, it's censorship. There are users of text-based browsers, people who are against the execution of client-side programs, people who only execute free software, etc., who cannot access the site now. Most privacy-aware people block JavaScript, that's why Tor Browser comes with NoScript.

The JavaScript code is obfuscated and proprietary (see excerpt below). I don't feel safe executing that code.

```
var s,t,o,p,b,r,e,a,k,i,n,g,f, CpnqtmZ={"GkTZAXiZZp":+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![])+(+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+!![]))/+((!+[]+!![]+[])+(!+[]+!![])+(!+[]+!![]+!![])+(+!![])+(+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]))};
```

**Comment by jorgesumle** [comment]
Now I can access to Liberapay. However, in the future, there should be another friendlier way to bypass it when "Under Attack", like a free software CAPTCHA. Even a simple "Introduce the result number of the following operation: six + 12" CAPTCHA would be enough to stop most scan traffic, being also friendly to disabled people because screen readers can read it aloud.

**Comment by Changaco** [comment]
Closing in favour of <https://github.com/liberapay/liberapay.com/issues/709> and <https://github.com/liberapay/liberapay.com/issues/2021>.
