### ISSUE TITLE
Avoid dependency on thirdparty service for avatars

### ISSUE THREAD

**Issue by Siesh1oo** [liberapay/salon#237]
Hi,

maybe this is just me, but the requirement to register with a third-party service just to set an avatar is a little annoying, not to say causing unnecessary worries from a security perspective.

I really like the concept of liberapay, but it should be possible to use the platform without connecting or authenticating to niche third-party services with little proven track record like https://www.libravatar.org/, ... especially for trivial issues like setting an avatar picture.

What are your thoughts?

Please keep up the good work!

**Comment by trebmuh** [comment]
related : #118 (and #183 a little bit), and https://github.com/liberapay/liberapay.com/issues/1138

(others : https://github.com/search?utf8=%E2%9C%93&q=org%3Aliberapay+avatar&type=Issues )

**Comment by Changaco** [comment]
See <https://github.com/liberapay/liberapay.com/issues/1044>.

**Comment by ofalk** [comment]
I know this is closed, but I wanted to mention, that libravatar is going to stay!
https://blog.libravatar.org/posts/Libravatar.org_is_not_going_away/

**Comment by trebmuh** [comment]
Thanks for passing on the information :+1:
