### ISSUE TITLE
News - July 2018

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#245]
This is Liberapay's monthly news thread.

cc @liberapay/media-managers

**Comment by Changaco** [comment]
Adding money by bank wire is now disabled.

![Screenshot of a payin page showing bank wires as "Currently unavailable"](https://user-images.githubusercontent.com/1581590/42375176-043de7a0-811b-11e8-835b-cc94231fec50.png)

**Comment by Changaco** [comment]
https://social.tchncs.de/@jaltek/100328673563497793

**Comment by trebmuh** [comment]
:+1: good answer

**Comment by trebmuh** [comment]
As some of you might already know, I'll be out-of-the-web until the beginning of August.
Have a good July month everybody!

**Comment by Changaco** [comment]
https://mastodon.xyz/@Liberapay/100363836114766451
https://twitter.com/liberapay/status/1017520023714312193

> Liberapay is in trouble, here's our blog post that explains the situation and what you should do if you're one of our 2000 active users: https://medium.com/liberapay-blog/liberapay-is-in-trouble-b58b40714d82

https://www.facebook.com/Liberapay/posts/1033264113498662

**Comment by Changaco** [comment]
https://mastodon.xyz/@Liberapay/100372188182919919

> The Mangopay exodus is proceeding well so far: €5100 and $600 have already been transferred from the wallets of donors to creators, while €4800 and $440 have been refunded to donors instead.
>
> (If you don't know what this toot is about you should read our blog post: https://medium.com/liberapay-blog/liberapay-is-in-trouble-b58b40714d82 )

**Comment by Changaco** [comment]
https://mastodon.xyz/@Liberapay/100390667586296997
https://twitter.com/liberapay/status/1019238604747440128

> To all of you who have chosen to transfer the money left in your wallets to the people you support: thank you! These donations transferred "in advance" now sum up to over €20000 and $3400!

**Comment by Changaco** [comment]
https://mastodon.xyz/@Liberapay/100429014093788998

> Tomorrow we will refund as much money as possible from donor accounts, so if you haven't distributed the remaining funds from your wallet to the people and projects you support, please do it now: https://liberapay.com/about/me/wallet/empty
>
> You can find more information in our blog post: https://medium.com/liberapay-blog/liberapay-is-in-trouble-b58b40714d82

https://twitter.com/liberapay/status/1021691699171676160
