### ISSUE TITLE
US withdrawals of Euros fail.. what now?

### ISSUE THREAD

**Issue by joeyh** [liberapay/salon#248]
I am in the US and have accumulated a sizable amount of Liberapay donations in USD and Euros. Since April I have been trying to withdraw it from Liberapay to my bank accounts. Every attempt has failed with different error messages from Mangopay.

With the Mangopay termination looming, I am now worried that I will never see that money, which  is a significant chunk of my income. I am trying to understand what's going to happen and what I can do about it.

Am I correct in surmising that the money is held by Mangopay, and so it won't migrate to whatever new payments method Liberapay ends up with?

Will Liberapay still be able to initiate withdrawals via Mangopay after the termination?

Also, has *anyone* in the US ever managed to successfully withdraw money? It would be helpful to have an example of a bank that is supported.

**Comment by joeyh** [comment]
I have so far tried to withdraw to Wells Fargo, which is a major US bank with international capabilities. I've tried using their SWIFT code and their ABA number, and neither USD nor Euros transfer. The failure reasons ranged from "121004: Specific case: please contact our Finance Team" to "121001: The bank wire has been refused" to "None"

I also tried a withdrawal to Sallie Mae Bank which is a smaller national bank and Mangopay seemed to not even know their ABA number (which was the correct ABA number as far as I can tell). (failure reasons "ABA invalid" and "invalid ABA code")

I also tried a Transferwise borderless account, but it turns out that account is not held in my name, and so Mangopay can't withdraw to it.

**Comment by mattbk** [comment]
I just successfully transferred into a US-based Ally bank account without issue. Unless you are getting an error after seeing this screen:

![image](https://user-images.githubusercontent.com/3729038/42652247-6a4fd9e8-85d7-11e8-8d4f-43062ba3e794.png)

**Comment by Changaco** [comment]
I haven't forgotten you Joey, I'll make sure you get your money somehow.

> Am I correct in surmising that the money is held by Mangopay, and so it won't migrate to whatever new payments method Liberapay ends up with?

In theory it could be migrated to one of Mangopay's competitors, but in practice it probably won't happen, because we need consent from each user so we're better off asking users to empty their wallets instead.

> Will Liberapay still be able to initiate withdrawals via Mangopay after the termination?

I don't actually know what will happen. It's quite possible that Mangopay will cut off our access to their API completely and expect us to send them withdrawal instructions by email. It wouldn't be the first stupid thing they did.

> Also, has *anyone* in the US ever managed to successfully withdraw money?

Yes, I'm pretty sure there have been some successful withdrawals to US bank accounts.

**Comment by Changaco** [comment]
@mattbk The errors come later. The success message is misleading, your withdrawal hasn't actually been approved and initiated by Mangopay yet, much less received by your bank.

**Comment by joeyh** [comment]
@mattbk please followup if it succeeds or fails for you..

@Changaco I realize you have confidentiality and nonprofit constraints, but it would be really helpful to know what they did that made it work. Perhaps you could reach out to some of the successful users and ask them to publically share what details they're comfortable with sharing about their withdrawals?

And @Changaco, it stinks that you're in this position, and thanks for everything you're doing to deal with it.

**Comment by joeyh** [comment]
Meanwhile I got on the phone with Wells Fargo's international transfers division and we went through the Liberapay withdrawal form together and made sure that I'm entering the right SWIFT code for Euro transfer, right bank address, etc. If this latest attempt fails, I'll be as sure as I can be that it was not due to a mistake of mine.

**Comment by joeyh** [comment]
My Euro withdrawal failed again.

Meanwhile, a friend has confirmed successful USD withdrawal today, to a local credit union in NY. (Using US routing number not SWIFT)

**Comment by mattbk** [comment]
My transaction succeeded.

**Comment by joeyh** [comment]
USD withdrawal to Wells Fargo succeeded using US routing number.

But most of my Liberapay donations are in Euros and I still am unable to withdraw them. 

Here are the instructions that Wells Fargo provides for reciving Euros by wire:

> Here are the wiring instructions for EUR and USD.  United States banks are not
> on the IBAN system, please tell your vendor to use your account number in place
> of an IBAN for the wire.  They may need to speak with their bank on how to
> process to a non-participating IBAN country.  Please be sure to fill in the
> account name and number before sending on.
> 
> Euro (EUR)
> 
> Intermediary Bank: Deutsche Bank AG Frankfurt AM Main
> 
> Intermediary Bank SWIFT BIC: DEUTDEFF
> 
> Beneficiary Bank: Wells Fargo Bank, N.A.
> 
> Beneficiary Bank SWIFT BIC: WFBIUS6WFFX
> 
> Beneficiary Bank Wire Routing Transit Number (RTN/ABA): 121000248
> 
> Beneficiary Bank Address:  420 Montgomery St., San Francisco, CA 94104
> (regardless of where your account is located)
> 
> Wells Fargo Account Holder Name:
> 
>  Wells Fargo Account Number:

The Liberapay form doesn't have a way to enter an intermediary bank. And probably the Mangopay API also lacks support for that.

**Comment by joeyh** [comment]
@Changaco any way we could do a manual euro withdrawl with all that needed information listed above? Or a one-time euro-to-USD conversion since I can withdraw USD?

**Comment by Changaco** [comment]
I'll forward the information to Mangopay and ask if they can do a manual transfer.

**Comment by Changaco** [comment]
@joeyh Could you fill the "Level 2" section in <https://liberapay.com/about/me/identity>? I realize it's annoying, but since you have more than €1000 in your wallet Mangopay will probably refuse withdrawals until you provide a "proof of identity".

**Comment by joeyh** [comment]
@Changaco oh, I was not making enough until the wallet emptying started.. Filled out Level 2! Waiting on a validation spinner..

**Comment by joeyh** [comment]
@Changaco sent email with my bank details filled in.

**Comment by joeyh** [comment]
Finally sucessfully withdrew some Euros in a test transaction.

I used a Transferwise borderless account. This provides a personal IBAN number that Euros can be sent to. Transferwise will then convert to USD and can withdraw to US bank accounts. (Have not completed that yet.)

If someone else needs to do this, be  careful: I had an earlier transfer, to Transferwise's SWIFT number, get hung up inside Mangopay and almost lost, because their SWIFT BIC they show to use is not an account in my name. Had to upgrade to a borderless account to get the IBAN, which does work.

@Changaco seems the manual transfer will not be needed unless my full withdrawal fails for some reason.

**Comment by mnh48** [comment]
can I know how many days it took for you to withdraw euro? and what's the description in bank statement? did it send out email after it is successful?

I initiated withdrawal of Euro 5 days ago then another Euro and USD yesterday.

Today I received money that I don't know from who but the amount is too far different from what I was withdrawing (it's far less) so I think it's not from them yet (or maybe partial amount?). I'll wait a few more days and see if I get the full amount.

The unknown money appeared as INW FTT - CR CASA - CELLLULL in my bank statement. I tried to search more info but no results or clue for where it came from.

On Liberapay, all of them appeared as SUCCEEDED, btw.

**Comment by revi** [comment]
I usually withdraw EUR to KRW savings account with other bank acting as an intermediary so it might be different, but for me it usually took 3-5 business days. This exodus means more transactions so maybe it can pile up but dunno for sure.

By the way, if you withdraw using SWIFT, your bank could charge you just for handling SWIFT transaction. (My bank charges $5 for incoming SWIFT transaction)

**Comment by LukeSmithxyz** [comment]
~~I'm not sure if this is a general problem, but I'm getting the same problem as @MuhdNurHidayat. I used the "emptying wallet" function several days ago, and though it emptied my wallet and now says on my statement ` withdrawal — succeeded `, I still haven't gotten any money in my bank account (an American bank with USD).~~

~~Not sure if a delay is typical behavior, but I'll voice it if it's relevant.~~

Ends up this was simply delay. The payment came through.

**Comment by ddevault** [comment]
I put in a withdrawl twice over the course of the past two weeks, both failed with:

```
Blocked due to the Bank Account User's KYC limitations (maximum debited or credited amount reached)
```

**Comment by Changaco** [comment]
@SirCmpwn Sorry about the cryptic error message from Mangopay, it means that you have to fill the "Level 2" section in <https://liberapay.com/about/me/identity>.

**Comment by ddevault** [comment]
The deadline has passed, will it still work?

**Comment by Changaco** [comment]
Yes, Mangopay hasn't cut off our API access yet, so everything still works for now.

**Comment by ddevault** [comment]
Thanks!

**Comment by joeyh** [comment]
Successfully got my money out via Wells Fargo (USD) and Transferwise Borderless (Euro), though the KYC almost made it fail at the last minute.

**Comment by mattbk** [comment]
My EUR finally arrived through US-based Ally Bank without needing to find an intermediary or call them up.

**Comment by mnh48** [comment]
> By the way, if you withdraw using SWIFT, your bank could charge you just for handling SWIFT transaction. (My bank charges $5 for incoming SWIFT transaction)

My bank do charge MYR3 for SWIFT transaction *after the money arrived*, it's just the original amount deposited to bank doesn't match up around 50%. Withdraw initiated 29 EUR in Liberapay, received in bank was around 17 EUR.

BUT, it looks like my latter withdrawal of EUR and USD has also arrived in my bank, and the amount is correct.

So, even though the first withdrawal doesn't match, I assume it might be deducted for some kind of verification fees or something on EU's end as the latter withdrawals I received are exactly the expected amount, so I guess it's okay.
