### ISSUE TITLE
Onboard @aandis

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#26]
@aandis Would you like to be added to the Liberapay org on GitHub and [the team on Liberapay](https://liberapay.com/Liberapay/)? :-)

**Comment by aandis** [comment]
Sure! :) I mostly focus on issues which involve some learning for me. And especially in this case, I'll try to send prs for stuff common between liberapay and gratipay. :)

**Comment by Changaco** [comment]
I've sent the invite for the GitHub org. You need to create a Liberapay account before I can invite you to the team there. ;-)

**Comment by aandis** [comment]
Awesome. :+1:

**Comment by aandis** [comment]
https://liberapay.com/aandis/ :)

**Comment by Changaco** [comment]
:-) Invite sent.

**Comment by aandis** [comment]
@Changaco sorry I haven't been active for a while. I have been busy with my full time job and won't be able to contribute anytime soon. You may remove me from the org if you'd like. I'll keep an eye out for active developments to liberapay though. :)

**Comment by Changaco** [comment]
Thanks for the news @aandis. :-)

Instead of removing you completely from the GitHub org I've created [a separate team for inactive code contributors](https://github.com/orgs/liberapay/teams/techs-inactive) and moved you there.

I'm not kicking you out of the Liberapay team, you can leave it yourself if you want.

I'm closing this issue now, of course you're welcome to reopen it whenever you want.
