### ISSUE TITLE
DSP2

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/salon#267]
Do you think the DSP2 will help us improve Liberapay? Here is an article (in French)

https://www.latribune.fr/entreprises-finance/banques-finance/paiement-la-directive-dsp2-entre-en-vigueur-c-est-quoi-764449.html

**Comment by Changaco** [comment]
This question was later answered in <https://github.com/liberapay/liberapay.com/issues/1394#issuecomment-475304526>:

> It's true that the PSD2 directive may eventually allow us to support direct SEPA transfers from one donor to one recipient, but that's of limited usefulness to a platform like Liberapay.
