### ISSUE TITLE
HackerOne program

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#269]
Three months ago [Liberapay's HakerOne program](https://hackerone.com/liberapay) was paused by @EdOverflow after I asked him via Gitter to disable it until the Mangopay crisis was over. Even though we're not completely done migrating away from Mangopay, we aren't in the middle of the crisis anymore, so maybe it's time to re-enable submissions? cc @karelorigin

**Comment by karelorigin** [comment]
Sure, I think it takes time for severe issues to be submitted anyways, might as well restart the program now.  @Changaco

**Comment by EdOverflow** [comment]
@Changaco, I have re-enabled the submission form so we should start seeing new reports again.

![image](https://user-images.githubusercontent.com/18099289/48673003-59631c00-eb3d-11e8-8b2b-bb85ec31d2f9.png)

**Comment by Changaco** [comment]
Thanks Ed. :slightly_smiling_face:
