### ISSUE TITLE
Onboard @benhc123

### ISSUE THREAD

**Issue by blrhc** [liberapay/salon#282]
Hello,
I did help out on Gratipay before it was closed and would be very keen to offer help as a security researcher for Liberapay (which I have also done for [GitHub](https://bounty.github.com/researchers/benhc123.html)).
Hope I can help out!

**Comment by Changaco** [comment]
Welcome.

We have a HackerOne program, <https://hackerone.com/liberapay>, managed by @EdOverflow. We also have a public list of known low-severity issues: <https://github.com/liberapay/liberapay.com/labels/Defense>.

**Comment by benhc123** [comment]
Hi @Changaco, that looks great. In the meantime, I've also started translating the project into Irish via Weblate, as it's a language that I'm fluent in.

**Comment by Changaco** [comment]
That's great, last I heard Irish translators were in short supply.

**Comment by benhc123** [comment]
They certainly are! I'm going to keep working on this - is there any chance I might be invited to the team on Liberapay? I'll only be taking a symbolic cent share until I can do something more significant to help out.

**Comment by Changaco** [comment]
I've sent you an invite.
