### ISSUE TITLE
Announce the launch

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#3]
Share on:
- twitter
- diaspora*, [original announce in French](https://framasphere.org/posts/1479384)
- reddit, possibly relevant subs: [/r/opensource](https://www.reddit.com/r/opensource), [/r/Crowdfunding](https://www.reddit.com/r/Crowdfunding), [/r/freesoftware](https://www.reddit.com/r/freesoftware), [/r/coolgithubprojects](https://www.reddit.com/r/coolgithubprojects)
- hackernews
- google+
- facebook: [Liberapay has a page](https://www.facebook.com/Liberapay-472128142945598/) (your help in maintaining it is very welcome, see #29)

Write:
- [x] create a blog for Liberapay and write a first post about the launch
- [x] linuxfr.org, see [the post I made about Gratipay back in the day](https://linuxfr.org/users/changaco/journaux/presentation-de-gratipay-pour-un-financement-durable-du-logiciel-libre)
- [ ] framablog.org

Please help spread the word, but **don't spam and don't flood (don't post everywhere at the same time, we need to share regularly, not all-in-one-day)**. Please post the links here so we can all see and participate. If you have ideas on where else to announce the launch, please post them here too.

**Comment by MartinDelille** [comment]
I just post it in a private facebook group for now. I'll be interested into working on the blog if it's a [jekyll](https://pages.github.com/) [github pages](https://pages.github.com/). Is there already something started somewhere?

**Comment by Changaco** [comment]
Nothing is started for the blog. I was thinking of using Medium in the beginning to avoid spending time setting up our own thing and to benefit from their community, then moving to a self-hosted thing on `blog.liberapay.org` later.

**Comment by Changaco** [comment]
I just announced the launch on SeenThis: http://seenthis.net/messages/457652.

**Comment by Changaco** [comment]
First tweet in French: https://twitter.com/Changaco/status/695239358677454848.

**Comment by Changaco** [comment]
In English on our official account: https://twitter.com/liberapaye/status/695245559783751680

**Comment by Changaco** [comment]
https://twitter.com/search?f=tweets&vertical=default&q=liberapay&src=typd

I'm going to put a twitter bot in our IRC channel (#liberapay on Freenode) later.

**Comment by Changaco** [comment]
Sent another tweet thanking MangoPay: https://twitter.com/liberapaye/status/695580892903804928

**Comment by Changaco** [comment]
I'm announcing our first payday of tomorrow, here's the tweet: https://twitter.com/liberapaye/status/697078981091323904

**Comment by Changaco** [comment]
Here's our new official Diaspora* account: https://framasphere.org/u/liberapay

**Comment by Changaco** [comment]
And here's a post in French on my personal Diaspora* account: https://framasphere.org/posts/1500220

**Comment by Changaco** [comment]
https://twitter.com/Changaco/status/698822161272807424

**Comment by Changaco** [comment]
I think we can draw the following conclusion: most of the time tweeting from an account that doesn't have many followers is like writing to `/dev/null`. Diaspora* is much better at reaching people who care, thanks to the tags.

**Comment by Changaco** [comment]
A link to Liberapay has been [posted on the French HackerNews](https://www.journalduhacker.net/s/u9d12x/liberapay_est_une_plateforme_de_dons_r_currents).

**Comment by MartinDelille** [comment]
I'll plus it if you send me an invite (I don't have an account yet)

**Comment by Changaco** [comment]
I'm not sure we really need more upvotes, but I've sent you an invite anyway.

**Comment by Changaco** [comment]
https://openfoodfrance.wordpress.com/2016/02/14/soutenez-open-food-france/

**Comment by Changaco** [comment]
https://www.reddit.com/r/coolgithubprojects/comments/476f48/liberapay_recurrent_donations_platform/

**Comment by Changaco** [comment]
BTW, we do have our own subreddit: [/r/liberapay](https://www.reddit.com/r/liberapay/).

**Comment by Changaco** [comment]
https://twitter.com/Korben/status/704583090216308736

**Comment by Changaco** [comment]
I've created a blog on Medium: https://medium.com/liberapay-blog. They seem to have exactly zero i18n/l10n options, and we don't want to rely on them anyway, so we still need a self-hosted one.

**Comment by Changaco** [comment]
http://philippe.scoffoni.net/liberapay-outil-financement-participatif/
https://twitter.com/pscoffoni/status/719087768496971777
https://www.facebook.com/Liberapay/posts/588416347983443

**Comment by Changaco** [comment]
https://www.journalduhacker.net/s/5awmsl/liberapay_un_nouvel_outil_de_financement_participatif

**Comment by Changaco** [comment]
We've published our first blog post in English on Medium: https://medium.com/liberapay-blog/a-new-platform-to-fund-work-on-open-source-projects-a97fac218cc7

I guess what we need to close this ticket is to publish one in French on linuxfr or framablog. @MartinDelille proposed in IRC to translate our English post, but would it fit the audiences of either of those sites? It wasn't written for them.

**Comment by MartinDelille** [comment]
The translation is in progress here: https://mensuel.framapad.org/p/Wc02svOXSP
You may be right saying it doesn't target the same audience, but maybe we can take it as a basis for the LinuxFR post?
