### ISSUE TITLE
[Language] Feeds -> Social Networks

### ISSUE THREAD

**Issue by alvaroadlf** [liberapay/salon#364]
The "Feeds" section refers to the social networks in which Liberapay has a presence, I think it would be much more appropriate to use "Social Networks" instead of "Feeds", it is much clearer -and also to translate- and more accurate.

**Comment by trebmuh** [comment]
@alvaroadlf do you have a link and/or a screenshot please?

**Comment by alvaroadlf** [comment]
> @alvaroadlf do you have a link and/or a screenshot please?

Sure, here it is 😉

![alt text](https://i.ibb.co/YDMcssz/screencapture-en-liberapay-about-feeds-2020-04-07-21-53-29.png "Feeds - Liberapay")

**Comment by fitojb** [comment]
@alvaroadlf Note that the most idiomatic term in English for what Spanish speakers call “redes sociales” is “social media,” not “social network,” as the latter term refers to the original concept in sociology.

**Comment by trebmuh** [comment]
@alvaroadlf I can see you point and I think it is a valid one. Thanks for opening this issue. Whether it is choosen "social networks" or "social medias" doesn't hurt my heart.
@Changaco what's you're recommendation here? I can make such a PR if you agree with this.

**Comment by Changaco** [comment]
"Feeds" is a little abstract, but I'm not sure what would be better. Maybe “Follow Us”.

**Comment by trebmuh** [comment]
@alvaroadlf @fitojb You're ok with that ?

**Comment by alvaroadlf** [comment]
> "Feeds" is a little abstract, but I'm not sure what would be better. Maybe “Follow Us”.

Follow Us 👌🏼

**Comment by trebmuh** [comment]
I've prepared a PR. I didn't change all the *.po since the will be updated in Weblate I'd guess, isn't @Changaco ?
