### ISSUE TITLE
Wikipedia scam

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#417]
We recently received the following email:

> Subject: Your Liberapay Wikipedia Page Has Been Tagged for conflicts of interest
>
> Hello
>
> I am a veteran Wikipedia editor with 7+ years experience. I noticed that your page has been tagged with {{COI}} tag for some time. This happens when the page has been created in exchange for monetary benefits which goes against Wikipedia policies, and might lead to credibility issues later on. 
>
> I can help you out. I wanted to reach out and inquire if you would like me to intervene to clean up the article and remove the {{COI}} tag. The tag is a nuisance and doesn't look good for the company's credibility in front of whoever is reading the page. 
>
> There will be a nominal fee of $450, paid via BTC or Bank transfer, and it will take about 72 hours. 
>
> Looking forward to your revert. 
>
> Thank you,
>
> Eric

Does someone know if we should report this to Wikipedia or if it's best to simply ignore it?

**Comment by trebmuh** [comment]
It looks to be a spam since there is no such a tag on the [LiberaPay page on Wikipedia](https://fr.wikipedia.org/wiki/Liberapay) neither on the other translated pages. It then looks more like an extortion spam attempt to me. It's probably fine to be ignored.

**Comment by Changaco** [comment]
The tag is on the English page: https://en.wikipedia.org/wiki/Liberapay

**Comment by trebmuh** [comment]
I didn't see it first. Thanks.
Anyway, the initial message you received still looks like an extortion spam attempt, because of the `There will be a nominal fee of $450, paid via BTC or Bank transfer, and it will take about 72 hours. ` sentence.
I've got no strong opinion about whether or not you need to contact wikipedia for that.

**Comment by revi** [comment]
It is against Wikipedia policy to engage in undisclosed paid editing. All paid editors MUST disclose their affiliation or payment details, and who paid them. Can you forward me the email (or give me the complete email including header) and I'll do the background job with dealing with Wikipedia internal people.

**Comment by revi** [comment]
And it is against Wikimedia Terms of Use to skip/ignore it. https://foundation.wikimedia.org/wiki/Terms_of_Use/en#paid-contrib-disclosure

**Comment by Changaco** [comment]
I've forwarded the email to @revi.
