### ISSUE TITLE
Watercooler - June 2016

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#42]
This is Liberapay's monthly "what's up?" thread. Previous: #36.

**Comment by Changaco** [comment]
@MartinDelille asked in IRC if we had tried to get the Twitter account that exactly matches our name ([@liberapay](https://twitter.com/liberapay)). The answer is yes, I contacted both the owner and Twitter (through their impersonation tool), neither responded.

**Comment by MartinDelille** [comment]
I tried again: https://twitter.com/martinodelilo/status/738359749113176064

**Comment by MartinDelille** [comment]
And also one of its followers: https://twitter.com/martinodelilo/status/738361557541916672
I sent a mail to the other, wait and see!

**Comment by Changaco** [comment]
Today Switzerland is holding a national referendum on basic income, which is an idea that influenced the way Liberapay works.

**Comment by Changaco** [comment]
As predicted by the polls the initiative for basic income was rejected. However, 23% voted in favor of it, which is not so bad, and the referendum generated worldwide press coverage for the idea of basic income, which is a big win for the movement. :-)

Tomorrow, back to working on funding our own basic incomes from donations via Liberapay!

**Comment by Changaco** [comment]
https://twitter.com/Changaco/status/739884275722522624

> Someone just posted a link to @liberapaye on Hacker News for the first time :-) https://news.ycombinator.com/item?id=11848605

**Comment by Changaco** [comment]
And in [/r/opensource](https://www.reddit.com/r/opensource/comments/4muvsn/liberapay_donations_platform_gittip_forkrevival/).

**Comment by Changaco** [comment]
[Stripe is now out of beta in France](https://stripe.com/blog/stripe-en-france), but they're still more expensive than MangoPay, and they probably still don't accept platforms like Liberapay.

**Comment by MartinDelille** [comment]
Ok. How many payement platform do we handle? Maybe it'll be cool to had some? Like Bitcoin?

**Comment by Changaco** [comment]
We rely entirely on MangoPay and we currently can't use any payment method that it doesn't support. The only other platform we've considered using is Uphold (https://github.com/liberapay/liberapay.com/issues/44), but last I heard their paperwork was insane (https://github.com/gratipay/gratipay.com/issues/3870#issuecomment-187718272).

I personally have no interest in adding support for Bitcoin. I also think it would probably bring us more shady users than good ones. Moreover, I know that Gratipay can't use Bitcoin for legal reasons, so we'd need to research whether we could or not.

**Comment by Changaco** [comment]
[Ask HN: Patreon for open source? | Hacker News](https://news.ycombinator.com/item?id=11868267) (via https://github.com/gratipay/inside.gratipay.com/issues/656#issuecomment-224886996)

**Comment by Changaco** [comment]
[Top Patreon Creators: Best + Popular + Highest Paid + Successful](https://graphtreon.com/top-patreon-creators) (found it in the aforementioned Hackers News thread)

**Comment by MartinDelille** [comment]
I spoke about bitcoin because I'm participating to the Blockfest in Paris this week-end.

Regarding the top patreon creators link, shall I post it on facebook?

**Comment by Changaco** [comment]
> Regarding the top patreon creators link, shall I post it on facebook?

No, if I thought we should share it I would have posted it in the news thread (#43).

**Comment by Changaco** [comment]
MangoPay has released a new version of [their documentation](https://docs.mangopay.com/).

**Comment by Changaco** [comment]
https://twitter.com/opencollect/status/742843048514736128

> We now have 32 awesome open source projects on Open Collective totaling 1198 contributors, 120k+ stars. Support them https://opencollective.com/opensource

**Comment by Changaco** [comment]
[A handy guide to making $$ in open source](https://github.com/nayafia/lemonade-stand)

**Comment by Changaco** [comment]
[The next generation of OpenShift Online is here](https://blog.openshift.com/next-generation-openshift-online/) (Not really, it's a developer preview with temporary accounts.)

**Comment by Changaco** [comment]
Shit has hit the fan. MangoPay has a problem with controversial people using its service.

**Comment by Changaco** [comment]
MangoPay has just destroyed Liberapay's neutrality.
