### ISSUE TITLE
Any recommendation for non anonymous donations?

### ISSUE THREAD

**Issue by DrAlta** [liberapay/salon#427]
Hi. I originally set up a patreon page and identified stake holders that way but Libreapay donors are anonymous.  I want people to have to contribute something but still get the the amount of effect they need to enter at a minimum.
 I was going to use OpenCollective but we're into sex education and Stripe said "Since Adult content and services is on our Restricted Businesses List, we cannot process payments on your behalf". 

Do you know of a non-profit alternative to patreon that allows adult content and patron perks?  Or An alternative method of selecting stake holders?

**Comment by Changaco** [comment]
No.

**Comment by Changaco** [comment]
> I want people to have to contribute something

Then you're not looking for a donation platform. A payment that is required in order to gain to access a resource isn't a donation, it's a purchase.
