### ISSUE TITLE
Does Liberapay moderate users?

### ISSUE THREAD

**Issue by throwaway72980742** [liberapay/salon#45]
In particular I have noted an openly neo-nazi white supremacist organisation being funded through your services. Do you have any policy on this matter?

**Comment by Changaco** [comment]
Liberapay is neutral, meaning that we only kick out users if we are required to do so by a law or contract ([article 10 of the bylaws](https://github.com/liberapay/liberapay.org/blob/v1/en/bylaws.md#article-10-neutrality)), we're still not sure if we have such an obligation regarding the user you're referring to (see our investigation in https://github.com/liberapay/liberapay.org/issues/11).

**Comment by throwaway72980742** [comment]
Thank you for clarifying your position. I understand it is a matter of principle and I respect that, however, I would urge you strongly to reconsider your position on such clear cut cases of racial hatred - not only for the good of humanity but also to protect yourself from legal ramifications. Kind regards.

**Comment by Changaco** [comment]
Time to close this, the user has been banned by our payment processor a while back, and there's a proposal to change our terms in https://github.com/liberapay/liberapay.org/issues/12#issuecomment-233150309.
