### ISSUE TITLE
a mastodon bot "against" liberapay ?

### ISSUE THREAD

**Issue by trebmuh** [liberapay/salon#472]
Today, I posted a message on Mastodon with a link to my liberapay account.
In a few second I had a message which looks to be against liberapay (or maybe I'm misunderstanding something).
See: https://mamot.fr/web/statuses/107319979371795307

**Comment by Changaco** [comment]
It's an anti-Cloudflare bot. The anti-Cloudflare mob has been spamming the Fediverse for a long time.

**Comment by trebmuh** [comment]
Strange, that's the first time I'm seeing it answering one of my posts.
