### ISSUE TITLE
Watercooler - July & August 2016

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#50]
This is Liberapay's monthly "what's up?" thread. Previous: #42.

**Comment by Changaco** [comment]
[Communs et économie : quelle cohabitation dans une perspective de transition ? - P2P Foundation](http://blogfr.p2pfoundation.net/index.php/2016/07/03/communs-economie-cohabitation-perspective-de-transition/) (it mentions Liberapay briefly)

**Comment by MartinDelille** [comment]
Shall I share it on facebook?

**Comment by Changaco** [comment]
[Flattr Plus update](http://blog.flattr.net/2016/07/flattr-plus-update/)

**Comment by Changaco** [comment]
BountySource sent this email to their users last week:

> As you may be aware, Bountysource is fully open-source. What you may not know is that Bountysource staff (Warren & David) are currently maintaining the service in their spare time. While the revenue we collect on transactions pays the bills and keeps the service alive, it does not provide much room for improvement.
> 
> We are launching a Salt campaign to address some of our immediate needs, including:
> 
> * Faster response times for customer support and cash out requests
> * High priority bug fixes and new development
> * Funding bounties for popular feature requests
> 
> If you want Bountysource to succeed, please consider contributing to our campaign!
> 
> ## [Support Bountysource!](https://salt.bountysource.com/teams/bountysource)
> 
> 
> Thanks,
> 
> [The Bountysource Team](https://www.bountysource.com/teams/bountysource)

**Comment by Changaco** [comment]
[Funding digital infrastructure](https://medium.com/@nayafia/funding-digital-infrastructure-8b1bf8b8e4cb)

[Roads and Bridges: The Unseen Labor Behind Our Digital Infrastructure](http://www.fordfoundation.org/library/reports-and-studies/roads-and-bridges-the-unseen-labor-behind-our-digital-infrastructure/) (full report, 143 pages)

**Comment by Changaco** [comment]
I have some non-Liberapay freelance work to do so I'm going to be less available for about a month (possibly more).

**Comment by Changaco** [comment]
[Gratipay's experiments in take-what-you-want compensation | Opensource.com](https://opensource.com/open-organization/16/7/compensating-employees-letting-them-take-what-they-want)

**Comment by Changaco** [comment]
https://github.com/liberapay/liberapay.com/pull/379 is the first PR in more than *2 months* that improves user experience in a really progressive way.

**Comment by Changaco** [comment]
There's a link to Liberapay in *[Unixcorn, trois mois plus tard : évolutions, remises en questions et stabilisation - LinuxFr.org](https://linuxfr.org/news/unixcorn-trois-mois-plus-tard-evolutions-remises-en-questions-et-stabilisation)*.

**Comment by Changaco** [comment]
[Ask HN: Getting paid to work on open source full-time?](https://news.ycombinator.com/item?id=6660923)
