### ISSUE TITLE
Machine translation

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#520]
I think we should use machine translations to stop having partially translated versions of the Liberapay website. The machine translations would only be defaults and would be marked as "fuzzy"; humans would be able and encouraged to review them and overwrite them if they're not good enough. [Weblate has an autotranslate add-on](https://docs.weblate.org/en/latest/admin/addons.html#addon-weblate-autotranslate-autotranslate) that can do exactly that, all I have to do is enable it, and reword the warning displayed at the top of an imperfectly translated page. What do y'all think?

![Screenshot of the form to enable Weblate's automatic translation add-on](https://user-images.githubusercontent.com/1581590/184825633-53dd5842-779e-407e-8610-cfc15d983fd4.png)

**Comment by trebmuh** [comment]
Sounds like a good idea to me.

**Comment by biskwikman** [comment]
Sounds good to me!

**Comment by jorgesumle** [comment]
The website should say "(partly) machine translated", not "imperfectly translated", because machine translations are sometimes right.

**Comment by Changaco** [comment]
I'm planning to replace the current warning

“The {language} translation of this page is not yet complete.”

with

“The translation of this page from English is not yet complete. {link_start}You can contribute{link_end}.”

and to add the new warning

“This page contains machine-translated text which hasn't yet been reviewed and might be inaccurate. {link_start}You can contribute{link_end}.”

**Comment by Changaco** [comment]
I have enabled the add-on.

We should probably increase Liberapay's donation to Weblate. I propose doubling it from €1 to €2 per week.

**Comment by trebmuh** [comment]
I agree

**Comment by biskwikman** [comment]
me too.

**Comment by Changaco** [comment]
I just realized that the automatic translation of Liberapay's website hasn't worked in two months because both DeepL and Google Translate have been removed as possible engines on Hosted Weblate. I have reconfigured it to use LibreTranslate instead, but quality will be lower, so we might have to migrate away from Hosted Weblate.

ping @nijel

**Comment by nijel** [comment]
You can still get for free API keys for both DeepL and Google Translate and install it on Liberapay project at Hosted Weblate. We just stopped to provide services paid by us site-wide.

**Comment by Changaco** [comment]
We now have DeepL and Google Translate again, and I also added Amazon Translate.
