### ISSUE TITLE
Handle CERFA for tax reduction

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/salon#57]
It'll be nice to handle automatic CERFA generation for project that can benefit it. Of course this is totally specific to France, but it could be a starting point.

Here is the CERFA document: http://www.impots.gouv.fr/portal/deploiement/p1/fichedescriptiveformulaire_5185/fichedescriptiveformulaire_5185.pdf

We'll need real users identity (not pseudo).

**Comment by Changaco** [comment]
This issue is about adding a feature to the software, it belongs in <https://github.com/liberapay/liberapay.com>.

**Comment by MartinDelille** [comment]
Ok sorry.
