### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/salon#58]
Is there any objection in creating a [Gitter](https://gitter.im) room for Liberapay?

**Comment by MartinDelille** [comment]
Preview is available here: https://github.com/liberapay/liberapay.com/tree/gitter#contact

**Comment by MartinDelille** [comment]
After closing liberapay/liberapay.com#388, I propose to use https://www.mattermost.org
It is good to have a running chat for informal communication. The problem with IRC is that you don't receive message when you are disconnected.

**Comment by Changaco** [comment]
[Gitter is open source | Hacker News](https://news.ycombinator.com/item?id=14694283)

**Comment by Changaco** [comment]
I've created <https://gitter.im/liberapay/salon>, and joined it via <https://irc.gitter.im/>.
