### ISSUE TITLE
Unnecessary warnings in Weblate?

### ISSUE THREAD

**Issue by jorgesumle** [liberapay/salon#581]
I'm starting to see this "mismatched full stop" warning on Weblate:

![Bildschirmfoto vom 2023-09-19 23-05-31](https://github.com/liberapay/salon/assets/14212780/e6832753-0374-4c3f-80d3-d1691dbe7045)

It's only where the "unused singular" strings appear. I don't know if it's a bug or if I should put something special for the unused singular. I can dismiss it when I get it, but maybe it's better for me to know why I get this warning.

**Comment by trebmuh** [comment]
Same here in French. For now, I dismissed it. But it looks like a bug to me.

**Comment by Changaco** [comment]
I'm pretty sure this isn't a new problem. I've seen punctuation warnings on unused singulars before.

**Comment by Changaco** [comment]
I've submitted a patch to Weblate. It should fix the problem, but there will still be warnings on French and Turkish translations, because their plural formulas are slightly different from English and other languages.
