### ISSUE TITLE
Go to RMLL 2017

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#62]
The RMLL is an event in France about free software, the 2017 will be in [Saint-Étienne](https://en.wikipedia.org/wiki/Saint-%C3%89tienne). An organizer reached out in IRC and asked if Liberapay would like to participate by doing a conference or having a booth. Who around here is potentially interested in that?

---

_Un organisateur des Rencontres Mondiales du Logiciel Libre 2017 qui auront lieu à [Saint-Étienne](https://fr.wikipedia.org/wiki/Saint-%C3%89tienne) nous a contacté sur IRC et demandé si ça nous dit d'aller y faire une conférence ou y tenir un stand. Qui serait potentiellement intéressé ici ?_

**Comment by Zatalyz** [comment]
Why not ! It's a good opportunity to speak about Liberapay. If I have help to write a conference, I try to get the better of my shyness an present our project on RMLL. I want more information on "how it is organized" : organizer provide host, payment of road fees or I must provide this, for exemple. Or "how long for a conference ?" And if we have a stand, they supply table and chair, I bring mine ?

___
Pourquoi pas ! C'est une bonne opportunité pour parler de Liberapay. Si j'ai de l'aide pour écrire une conférence, je veux bien essayer de surmonter ma timidité et présenter notre projets aux RMLL. Je veux aussi plus d'information sur comment c'est organisé. Les organisateurs prennent-ils en compte l'hébergement et les frais de route, ou faut-il prévoir un budget pour ça ? Combien de temps doit faire la conférence (1h, 30min, autre) ? Et si nous avons un stand, ils fournissent tables et chaises ou j'amène les miennes ?

**Comment by MartinDelille** [comment]
I live in Lyon so it'll be possible for me to be there if it doesn't conflict with my job obligations.

Je vis à Lyon donc c'est envisageable que j'y aille si les horaires ne sont pas trop contraignante.

**Comment by Changaco** [comment]
Closing in favor of #99.
