### ISSUE TITLE
Recover twitter liberapay account

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/salon#70]
Following #42, it'll be nice to recover https://twitter.com/liberapay (or change name #56 ).

I try to reach two times the owner [directly](https://twitter.com/martinodelilo/status/738359749113176064) and through [one of it's follower](https://twitter.com/martinodelilo/status/738361557541916672). Any help or retweet would be appreciated (cc @liberapay/media-managers ).

I also sent a mail to http://www.silversailtourism.com

**Comment by KindlyFire** [comment]
[This](http://fusible.com/2011/06/how-to-get-a-twitter-username-thats-already-taken-hint-its-easy-i-got-mine/) might help

**Comment by MartinDelille** [comment]
Ok I performed the first step signaling the liberapay twitter account.

**Comment by davidak** [comment]
This issue can get closed now.

**Comment by Calinou** [comment]
The Twitter account is now [@liberapay](https://twitter.com/liberapay) since a few weeks ago, closing.
