### ISSUE TITLE
News - September 2016

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#73]
This is Liberapay's news thread, its purpose is to help us achieve #29.

cc @liberapay/media-managers

**Comment by Changaco** [comment]
https://framasphere.org/posts/2158007

**Comment by Changaco** [comment]
English version: https://framasphere.org/posts/2161388

**Comment by Changaco** [comment]
I've scheduled a tweet for tomorrow.

**Comment by Changaco** [comment]
Someone has asked us if we have a Diaspora* account in French. I would prefer using a single account, but support for multilingual accounts doesn't seem to be a priority upstream (<https://github.com/diaspora/diaspora/issues/3513>), so maybe we should create a second account. Alternatively we could start using language-specific tags (e.g. #liberapay_en #liberapay_fr).

**Comment by Changaco** [comment]
https://twitter.com/liberapaye/status/772763488003366912

**Comment by Changaco** [comment]
and https://twitter.com/liberapaye/status/772780484443136000

**Comment by Changaco** [comment]
Nadia Eghbal's report is being translated into French by the Framalang team: [Avec « Des routes et des ponts », la voie est libre – Framablog](https://framablog.org/2016/09/12/des-routes-et-des-ponts-1/). Although this isn't news about Liberapay it's something that we can share with our French users, as some of them may find it interesting.

**Comment by MartinDelille** [comment]
Shared on Facebook: https://www.facebook.com/Liberapay/posts/657325694425841
