### ISSUE TITLE
News - October 2016

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#79]
This is Liberapay's news thread, its purpose is to help us achieve #29.

cc @liberapay/media-managers

**Comment by Changaco** [comment]
A new blog post in French mentioning Liberapay: [Repensez l’argent et expérimentez le prix libre !](https://ploum.net/repensez-largent-et-experimentez-le-prix-libre/) The author currently receives €0.75 per week on Liberapay, I hope it'll go higher, he deserves it.

**Comment by Changaco** [comment]
Shared it in French on Diaspora*: https://framasphere.org/posts/2268878

**Comment by MartinDelille** [comment]
Shared on facebook: https://www.facebook.com/Liberapay/posts/669223633236047

**Comment by Changaco** [comment]
First announcement of the conference (in French): https://framasphere.org/posts/2312152

**Comment by Changaco** [comment]
Announcement in French on Twitter: https://twitter.com/liberapaye/status/787931908286124033

**Comment by MartinDelille** [comment]
Shared on facebook: https://www.facebook.com/Liberapay/posts/674520612706349

**Comment by Changaco** [comment]
Thanks. In addition to your post I've "attached" the event to our page to give it more visibility.

**Comment by Changaco** [comment]
https://twitter.com/liberapaye/status/791917807998906368

> Good news: signing up to donate on https://liberapay.com/ is now easier, you no longer need to provide a username and password. :-)
