### ISSUE TITLE
Why Liberapay, and what are its differences with Gratipay

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#8]
Picking up from https://github.com/liberapay/liberapay.com/issues/64#issuecomment-178644904 in which @SimonSarazin asked:

> It's maybe an other thread, but i don't clearly see what will be the difference between Gratipay and Liberapay. Is there any information about it ?

We do have [a FAQ entry about differences with other platforms](https://liberapay.com/about/faq#differences) that you should read first if you haven't already.

Let's talk specifically about Gratipay here.

Why was Liberapay started? What happened to Gratipay? The way I see it, two things:
- bad luck: Gratipay was basically started in the wrong country, the financial regulations in the US are problematic, and no payment processor (that we know of, at least) exists there that fills all the paperwork for you like Mangopay does in Europe
- questionable decisions: one in particular, kicking out users, [pushed me to leave](http://changaco.oy.lc/blog/goodbye-gratipay/).

What are the differences between the two sites?

Firstly, the differences born out of the [Gratipay 2.0 relaunch](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077):
- Gratipay dropped tips to individuals, focusing only on "teams" (but they're not really teams yet). Liberapay kept donations to individuals, and teams that actually work.
- Gratipay requires all teams to be approved, a process that takes more than a week. Liberapay is neutral (it's engraved in [its bylaws](https://github.com/liberapay/liberapay.org/blob/master/en/bylaws.md)) and the account creation is immediate.
- Due to the legal obstacles in the US, Gratipay is no longer a donation platform, it's a marketplace where you purchase vague services from teams. Liberapay is explicitly a donations platform, in fact other kinds of payments are forbidden by [its terms of use](https://liberapay.com/about/legal#terms).
- Gratipay tries to hold as little money as possible:
  - You have to set up a Paypal account before you can receive any money. Liberapay only requires basic identity information for that, and can send money directly to your bank account without going through Paypal.
  - A "dues" system was implemented, it makes your income more unpredictable because the risk that patrons will fail to pay when the time comes is higher. Liberapay is designed to stabilize user income, donations are funded in advance and we send an email to donors when their balance is low.

Other differences:
- Liberapay is a non-profit organization, Gratipay is a business.
- The payment processing fees when using Gratipay total more than 5% end-to-end, all going to Paypal. Liberapay is cheaper, around 3% end-to-end in the SEPA zone, and possibly still less than 5% outside even with payout fees.
- Liberapay has started implementing a real communities feature, to address the fact that the problem isn't just money but also communication.
- I'm pretty sure Liberapay's code is cleaner, which may not seem important to you, but it means that I can implement new features faster.
- Liberapay doesn't have the "Gittip crisis" ball and chain.

That's everything I can think of at the moment. I hope this post won't look like a hit piece to the people who will read it.

Ping @whit537 for transparency, feel free to express your point of view. ;-)

**Comment by aggsol** [comment]
What was the "Gittip crisis"?

**Comment by mattbk** [comment]
http://geekfeminism.wikia.com/wiki/Gittip_crisis. See also https://github.com/gratipay/inside.gratipay.com/issues/319.

**Comment by Changaco** [comment]
From my point of view the crisis was a storm in a teacup, and it had pretty much nothing to do with Gittip.

Unfortunately it has done a lot of damage. I've recently seen someone use the "Gittip crisis" to justify wanting to keep some discussions about a group of open source projects private.

**Comment by Changaco** [comment]
This thread is still regularly mentioned and read so I think that a small update is in order. The original comment was written only a few days after the launch of Liberapay, since then the platform has evolved, and so has Gratipay.

First, something I forgot to say in my original comment: Liberapay users have control over how much money they add into their account and when, whereas Gratipay charges credit cards automatically with no possible customization. The situation is similar for withdrawals.

Here are some of the changes on our side that haven't been replicated in Gratipay:

- language subdomains, e.g. https://fr.liberapay.com/ for French
- support for GitLab.com, LinuxFr.org, and Mastodon accounts
- bank transfers as an alternative way of funding one's donations
- support for monthly and yearly donation amounts
- creation and settlement of invoices for organizations (still in restricted beta, <https://github.com/liberapay/liberapay.com/issues/505>)
- temporal symmetry in donations to teams (<https://github.com/liberapay/liberapay.com/pull/599>)

(Most of those were listed in our blog post [The First Year of Liberapay](https://medium.com/liberapay-blog/the-first-year-of-liberapay-e57a3e08a662).)

On the other hand Gratipay has [NPM integration](https://gratipay.news/integrating-npm-39333109419d), there is no equivalent to that in Liberapay yet.

**Comment by Changaco** [comment]
I guess it's time to close this issue since Gratipay is shutting down.
