### ISSUE TITLE
News - November 2016

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#85]
This is Liberapay's news thread, its purpose is to help us achieve #29.

cc @liberapay/media-managers

**Comment by Changaco** [comment]
From <https://github.com/liberapay/liberapay.com/issues/85#issuecomment-258676107>:

> We now have basic support for monthly and yearly donation amounts. In reality all donations are still processed weekly, but now users can input a monthly or yearly donation amount and the server automatically computes the weekly equivalent. You can see what it looks like on <https://liberapay.com/Liberapay/donate> for example.

That deserves an announcement, along with https://github.com/liberapay/salon/issues/79#issuecomment-256863982 on networks where it hasn't been relayed yet. As usual I'm going to do Twitter and Diaspora*.

**Comment by Changaco** [comment]
Here's a screenshot in English:

![spectacle n20147](https://cloud.githubusercontent.com/assets/1581590/20037511/ccd887d0-a420-11e6-9277-997ca5ad58f7.png)

and the same in French:

![spectacle l20147](https://cloud.githubusercontent.com/assets/1581590/20037506/a3b8a790-a420-11e6-984d-cbacf944d4a1.png)

**Comment by Changaco** [comment]
First one in French: https://framasphere.org/posts/2399143

I ended using only the first half of the screenshot.

**Comment by Changaco** [comment]
I've posted a link to the above on Twitter: https://twitter.com/Changaco/status/795553265861689344

**Comment by Changaco** [comment]
First one in English: https://framasphere.org/posts/2402420

**Comment by Changaco** [comment]
https://twitter.com/liberapaye/status/795616042970071040

> We now have basic support for monthly and yearly donation amounts! (Transfers still happen weekly, amounts are converted automatically.)

**Comment by Changaco** [comment]
Hey @MartinDelille :-) Please let me know if you're too busy to do the Facebook posts so I'll know if I should do them myself.

**Comment by MartinDelille** [comment]
No it's fine I just posted it: https://www.facebook.com/Liberapay/photos/a.608265059331905.1073741827.472128142945598/687620004729743/?type=3&theater

**Comment by Changaco** [comment]
Can you post another one in French? I think most of our Facebook audience is French.

Did you know that Facebook supports multilingual posts? You simply need to click on "Écrire la publication dans une autre langue":

![spectacle m24199](https://cloud.githubusercontent.com/assets/1581590/20097260/d91ed9e8-a5ad-11e6-9d04-17c6b66d20b1.png)

However I've never found how to turn a publication into a multilingual one after it's been posted.

**Comment by MartinDelille** [comment]
Done: https://www.facebook.com/Liberapay/photos/a.608265059331905.1073741827.472128142945598/688064331351977/?type=3&theater

I didn't know about multilingual post!

**Comment by revi** [comment]
>However I've never found how to turn a publication into a multilingual one after it's been posted.

Editing the posted article allows to do that but when I did that for my personal account it messed up. Just deleting and re-posting is better. (If someone wonders, I use English and Korean - when I convert Korean only article to multilingual post (=English), Korean part is stripped out and only English one is shown regardless of target users' language.)

**Comment by Changaco** [comment]
https://linuxfr.org/news/liberapay-plateforme-libre-de-dons-recurrents

https://www.facebook.com/Liberapay/posts/700824563409287
