### ISSUE TITLE
Liberapay isn't listed on MOSS/Friends page

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#89]
https://twitter.com/liberapaye/status/801356873857462272

> @.gerv Can you also add us? We're an open source recurrent donations platform based in Europe.

**Comment by Changaco** [comment]
I'm sending an email since my tweet was either not seen or ignored.

**Comment by Changaco** [comment]
Here's the suggestion I've just sent:

> [Liberapay](https://liberapay.com/) is an [open source](https://github.com/liberapay) recurrent donations platform whose primary purpose is to help fund FOSS. Its currency is the euro and its legal structure is a non-profit organization based in France. The service was launched in early 2016, it has quite a few features and is translated into several languages. Everyone is welcome on Liberapay: individuals, nonprofits, businesses, and even [collectives that don't have a legal entity](https://liberapay.com/about/teams).

**Comment by Zatalyz** [comment]
That seems cool :)

**Comment by Changaco** [comment]
Liberapay now appears on https://wiki.mozilla.org/MOSS/Friends :-)

**Comment by Changaco** [comment]
https://twitter.com/liberapaye/status/804718830434091008

> Liberapay now appears on https://wiki.mozilla.org/MOSS/Friends
>
> You can read about @.mozilla's open source support program here: http://www.mozilla.org/moss
