### ISSUE TITLE
News - January 2017

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#97]
This is Liberapay's news thread, its purpose is to help us achieve #29.

cc @liberapay/media-managers

**Comment by Changaco** [comment]
https://www.facebook.com/Liberapay/posts/717877835037293

> Bonne année à tous !
> 
> Maintenant que 2016 est terminée, voici quelques chiffres sur cette première année de fonctionnement de Liberapay :
> 
> Plus de 500 personnes et 60 équipes ont rejoint Liberapay. 124 utilisateurs ont donné ou reçu de l'argent la dernière semaine de 2016.
> 
> Plus de 17 000 € sont entrés dans Liberapay. De ceux-là 4 400 € ont déjà été retirés vers les comptes bancaires des bénéficiaires. Malheureusement environ 7 000 € ont dû être remboursés pour cause de fraude ou de bannissement du bénéficiaire par notre opérateur de paiement (ces choses nous ont fait perdre beaucoup de temps en 2016).
> 
> À l'heure actuelle 256 dons hebdomadaires (ou promesses de dons) sont actives et financées, pour un total de 386 € par semaine, soit 20 000 € par an. Un grand merci aux 91 donateurs !
> 
> Depuis le lancement du site en février plus de 900 changements ont été effectués dans le code du site : https://github.com/liberapay/liberapay.com/graphs/contributors?from=2016-02-03&to=2016-12-28&type=c
> 
> Nous, l'équipe Liberapay, avons reçu 766 €. Si vous estimez que nous méritons plus, nous vous invitons à faire un don sur https://fr.liberapay.com/Liberapay/donate et à partager ce message ! Pas besoin de donner beaucoup, chaque euro compte et fait plaisir. :-)

---

> Happy new year everyone!
> 
> Now that 2016 is ended, here are some stats on our first year of activity:
> 
> More than 500 people and 60 teams have joined Liberapay. 124 users sent and/or received money in the last week of 2016.
> 
> More than 17000€ have entered Liberapay. Of those 4400€ have already been paid out to the bank accounts of 35 recipients. Unfortunately about 7000€ had to be refunded because of fraud or the recipient getting banned by our payment processor (these things wasted a lot of our time in 2016).
> 
> As of now 256 weekly donations (or pledges) are set up and funded, totaling 386€ per week, 20000€ per year. Many thanks to the 91 donors!
> 
> Since we launched in February more than 900 commits landed in our main code repository: https://github.com/liberapay/liberapay.com/graphs/contributors?from=2016-02-03&to=2016-12-28&type=c
> 
> We, the Liberapay team, have received 766€. If you think we deserve more than that, please donate on https://liberapay.com/Liberapay/donate and share this message! You don't have to donate a lot, every euro counts and warms our hearts. :-)

---

![spectacle x15817](https://cloud.githubusercontent.com/assets/1581590/21581362/f022b734-d02f-11e6-82d4-c7549be9e33f.png)
![spectacle s15558](https://cloud.githubusercontent.com/assets/1581590/21581361/eeaaaca4-d02f-11e6-9375-d13455993967.png)

**Comment by Changaco** [comment]
https://framasphere.org/posts/2646844

**Comment by Changaco** [comment]
https://framasphere.org/posts/2646884 (French)

**Comment by Changaco** [comment]
Next: the new design of the history page (https://github.com/liberapay/liberapay.com/pull/476).

**Comment by Changaco** [comment]
https://twitter.com/liberapaye/status/815916030136582144

> To kick off 2017 we've greatly improved the page that displays your transaction history! Check out yours: https://liberapay.com/about/me/wallet/

![spectacle x13583](https://cloud.githubusercontent.com/assets/1581590/21590180/aeef9f46-d0f9-11e6-8121-0654b5c253ec.png)

**Comment by Changaco** [comment]
(The account used for the screenshot is https://liberapay.com/LiberapayOrg/ since its finances are a public matter anyway.)

**Comment by Changaco** [comment]
Similar tweet in French:

https://twitter.com/liberapaye/status/816226356992311297

> Pour vous aider à faire le bilan de 2016, nous avons grandement amélioré la page d'historique de votre compte : https://liberapay.com/about/me/wallet/

![spectacle x13544](https://cloud.githubusercontent.com/assets/1581590/21604905/1415478e-d1a6-11e6-89cd-691f53dd3e72.png)

**Comment by Changaco** [comment]
Sentry is now sponsoring our use of their hosted service, in addition to mentioning them on the website (<https://github.com/liberapay/liberapay.com/issues/484>) let's thank them on social media too.

![spectacle m30069](https://cloud.githubusercontent.com/assets/1581590/21623565/44dff316-d203-11e6-86b3-a6039882da1e.png)

**Comment by Changaco** [comment]
Holy shit, https://liberapay.com/davidrevoy/ joined Liberapay a month ago and I missed it! Let's welcome him, better late than never.

**Comment by Changaco** [comment]
https://twitter.com/liberapaye/status/817411905287520260

> Are you familiar with the open-source webcomic http://www.peppercarrot.com/? Well, you can help fund it on Liberapay! https://liberapay.com/davidrevoy/

**Comment by Changaco** [comment]
[Patreons to support open source projects? Please share. - /r/linux](https://www.reddit.com/r/linux/comments/5omtvg/patreons_to_support_open_source_projects_please/)

> I've recently gone all in on Linux and I'm cancelling my Adobe Creative Cloud subscription, packing up my Affinity software, and putting away my Mac and Windows based video editors, game dev & web dev tools.
>
> Now I want to take the money I was putting into software for these platforms and put it towards supporting great Linux / open source projects instead.

**Comment by Changaco** [comment]
The videos of *Capitole du Libre 2016* are online! Here's the Liberapay presentation by me and @Zatalyz: <http://videos2016.capitoledulibre.org/enjeux-du-libre/trupin-coste-liberapay.mp4>, it's in French of course, and here's the full list of videos: <https://2016.capitoledulibre.org/videos.html>.

**Comment by Changaco** [comment]
https://twitter.com/liberapaye/status/825016501493125120

> La vidéo de la conférence sur Liberapay au @capitoledulibre 2016 est en ligne : http://videos2016.capitoledulibre.org/enjeux-du-libre/trupin-coste-liberapay.mp4 À partager sans modération ! 😄

**Comment by Changaco** [comment]
https://framasphere.org/posts/2778673

> ### Liberapay… en vidéo !
>
> [Les vidéos du Capitole du Libre 2016 sont désormais disponibles](https://2016.capitoledulibre.org/videos.html).
>
>**[Lien direct vers celle de la conférence sur Liberapay](http://videos2016.capitoledulibre.org/enjeux-du-libre/trupin-coste-liberapay.mp4).**
>
>Un beau cadeau une semaine avant le premier anniversaire du lancement de Liberapay. :-)
>
>#Liberapay #conférence #cdl2016 #libre #logiciel_libre #financement_participatif #dons #french #fr

**Comment by Changaco** [comment]
https://www.facebook.com/Liberapay/posts/731332803691796

**Comment by trebmuh** [comment]
Chouette conf', merci.
