### ISSUE TITLE
Go to conferences in 2017

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#99]
Who's going where this year? ping @Zatalyz @MartinDelille

Two conferences have been previously mentioned:

- [JDLL](http://www.jdll.org/) | April 1st-2nd | [Lyon](https://en.wikipedia.org/wiki/Lyon) | previous ticket: #68
- [RMLL](https://2017.rmll.info/) | July 1st-7th | [Saint-Étienne](https://en.wikipedia.org/wiki/Saint-%C3%89tienne) | previous ticket: #62

If you know of other conferences we could/should go to, please comment.

**Comment by Zatalyz** [comment]
I'm ok to go on JDLL and RMLL and speak about Liberapay, with the same conference as Capitole du Libre.

**Comment by danielegobbetti** [comment]
A conference with a small but loyal audience (see [last edition pictures](https://www.flickr.com/photos/free-software-center/albums/72157676647136705) to get an idea of the numbers) is https://www.sfscon.it/ 

I can get you in touch with the organizers if interested! 

[SFScon](https://www.sfscon.it/) | November 11 | [Bolzano](https://en.wikipedia.org/wiki/Bolzano)

**Comment by Changaco** [comment]
@Zatalyz Have you submitted a proposal for JDLL? It looks like the deadline is February 14th.

**Comment by Changaco** [comment]
[RMLL 2017 : l'appel à contributions est ouvert !](https://linuxfr.org/news/rmll-2017-l-appel-a-contributions-est-ouvert)

**Comment by Changaco** [comment]
We've received an invitation to join an event in [Rennes](https://en.wikipedia.org/wiki/Rennes) on May 12-13 about visual art and video games. Website: http://afgral.org

I've forwarded the message to @Zatalyz since she's closer to the video game world than me, however if she can't come I should be able to (I pass through Rennes every time I go in Brittany).

**Comment by Changaco** [comment]
The deadline for RMLL talk proposals is Friday.

The slides from cdl2016 need to be updated for the JDLL presentation on Saturday, the screenshots are outdated.

**Comment by Changaco** [comment]
I'm about to submit the proposal for the RMLL.

Summary in French:

> Comment financer le libre de manière stable et équitable ? Notre réponse à ce problème délicat est Liberapay (https://fr.liberapay.com/), une plateforme avancée de dons récurrents. Dans cette conférence nous expliquerons comment Liberapay facilite à la fois la collecte des dons, l'utilisation des fonds récoltés, et une répartition juste des montants des deux côtés (donateurs et bénéficiaires).

And in English:

> How can we fund open source projects (not just software) in a stable and fair way? Our answer to this delicate issue is Liberapay (https://en.liberapay.com/), an advanced recurrent donations platform. In this conference we will explain how Liberapay helps projects collect donations and use the money, as well as how it encourages splitting the amounts fairly on both sides (donors and recipients).

**Comment by Changaco** [comment]
The Liberapay presentation at the Libre Software Meeting will be on July 5th (Wednesday) at 3pm. It'll be in French. https://prog2017.rmll.info/programme/

**Comment by Changaco** [comment]
The presentation happened on schedule and was okay, here's a photo:

![](https://pbs.twimg.com/media/DD-TRldXcAAEM5X.jpg:large)

(from <https://twitter.com/chantier_libre/status/882586008256229376>)

**Comment by Changaco** [comment]
Next conferences we could join:

- [PyConFr](https://www.pycon.fr/2017/) | September 21st-24th | [Toulouse](https://en.wikipedia.org/wiki/Toulouse) | [call for participation](https://cfp.pycon.fr/cfp/)
- [Capitole du Libre](https://2017.capitoledulibre.org/) | November 18th & 19th | [Toulouse](https://en.wikipedia.org/wiki/Toulouse) | @Zatalyz intends to submit a talk proposal.
